/**
 * =============================================================================
 * TITech Community Capital LTD
 * Enterprise Airtel Payment Intelligence Explainability Store
 * =============================================================================
 *
 * File:
 *   backend/modules/payment/airtel/intelligence/governance/explainabilityStore.js
 *
 * Architectural role
 * ------------------
 * Durable evidence/provenance boundary for explanations generated by the Airtel
 * payment intelligence and governance stack.
 *
 * The store preserves the decision evidence required to answer:
 *   - What decision was produced?
 *   - Which governance/policy/model versions contributed?
 *   - Which rules/signals materially affected the outcome?
 *   - What evidence was present, missing, stale or contradictory?
 *   - What controls or approval requirements followed?
 *   - What uncertainty/confidence information was available?
 *   - Can the stored explanation be cryptographically verified later?
 *
 * Architectural position
 * ----------------------
 *
 *   Airtel Payment / Financial Context
 *                 |
 *                 v
 *       Intelligence + Governance Engines
 *                 |
 *                 v
 *            Explanation Builder
 *                 |
 *                 v
 *          Explainability Store
 *                 |
 *          +------+------+
 *          |             |
 *          v             v
 *      Audit Ledger   Support / Ops / Review
 *
 * Important boundaries / non-responsibilities
 * --------------------------------------------
 * - NOT the financial source of truth.
 * - NOT the canonical double-entry accounting ledger.
 * - NOT a payment execution or settlement service.
 * - NOT an authorization/RBAC service.
 * - NOT an AML/KYC/sanctions source of truth.
 * - NOT a model-serving or inference engine.
 * - NOT a policy engine.
 * - NOT a replacement for immutable audit storage.
 * - NOT a raw-feature warehouse.
 * - NOT permitted to persist provider secrets, tokens, OTPs, PINs, credentials,
 *   raw authorization headers, raw provider payloads or unnecessary raw PII.
 *
 * Production principles
 * ---------------------
 * 1. Tenant isolation is mandatory by default.
 * 2. Provider scope is Airtel by default.
 * 3. Explanations are append-only and versioned by explanation record ID.
 * 4. A deterministic fingerprint identifies semantic explanation contents.
 * 5. Sensitive values are redacted or represented by stable digests.
 * 6. Model/policy provenance is explicit and versioned.
 * 7. Explanation records are bounded in size and depth.
 * 8. Idempotent writes are scoped by tenant + idempotency key.
 * 9. Persistence is injected; the service itself owns no durable state in
 *    production.
 * 10. Cryptographic verification detects post-write mutation.
 * 11. Explanation generation never grants execution authority.
 * 12. Human-readable rationale is derived from structured evidence, not from
 *     unconstrained model-generated prose.
 * 13. Retry-equivalent explanations remain idempotently equivalent even when
 *     record identifiers or server timestamps differ.
 *
 * Module format
 * -------------
 * Native ESM. Node.js built-ins only. No project-internal static imports are
 * used in order to reduce circular dependency risk.
 * =============================================================================
 */

import { createHash, createHmac, randomUUID } from 'node:crypto';

export const ENGINE_NAME = 'airtel-explainability-store';
export const ENGINE_VERSION = '1.0.0';
export const COMPONENT = ENGINE_NAME;
export const PROVIDER = 'AIRTEL';
export const SCHEMA_VERSION = 1;
export const HASH_ALGORITHM = 'sha256';

export const EXPLANATION_TYPES = Object.freeze({
  GOVERNANCE_DECISION: 'GOVERNANCE_DECISION',
  POLICY_DECISION: 'POLICY_DECISION',
  RISK_DECISION: 'RISK_DECISION',
  PREDICTION_DECISION: 'PREDICTION_DECISION',
  RECOMMENDATION_DECISION: 'RECOMMENDATION_DECISION',
  APPROVAL_DECISION: 'APPROVAL_DECISION',
});

export const EXPLANATION_OUTCOMES = Object.freeze({
  ALLOW: 'ALLOW',
  ALLOW_WITH_CONTROLS: 'ALLOW_WITH_CONTROLS',
  REQUIRE_REVIEW: 'REQUIRE_REVIEW',
  REQUIRE_APPROVAL: 'REQUIRE_APPROVAL',
  BLOCK: 'BLOCK',
  CONFLICT: 'CONFLICT',
  STALE: 'STALE',
  INVALID: 'INVALID',
  INDETERMINATE: 'INDETERMINATE',
});

export const CONTRIBUTION_DIRECTIONS = Object.freeze({
  POSITIVE: 'POSITIVE',
  NEGATIVE: 'NEGATIVE',
  NEUTRAL: 'NEUTRAL',
  UNKNOWN: 'UNKNOWN',
});

export const SIGNIFICANCE_LEVELS = Object.freeze({
  NONE: 'NONE',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});

export const UNCERTAINTY_TYPES = Object.freeze({
  NONE: 'NONE',
  MISSING_EVIDENCE: 'MISSING_EVIDENCE',
  STALE_EVIDENCE: 'STALE_EVIDENCE',
  CONFLICTING_EVIDENCE: 'CONFLICTING_EVIDENCE',
  LOW_CONFIDENCE: 'LOW_CONFIDENCE',
  MODEL_UNAVAILABLE: 'MODEL_UNAVAILABLE',
  POLICY_UNAVAILABLE: 'POLICY_UNAVAILABLE',
  ENGINE_ERROR: 'ENGINE_ERROR',
  OFFLINE_STATE: 'OFFLINE_STATE',
});

export const EXPLAINABILITY_ERROR_CODES = Object.freeze({
  INVALID_INPUT: 'EXPLAINABILITY_INVALID_INPUT',
  TENANT_REQUIRED: 'EXPLAINABILITY_TENANT_REQUIRED',
  PROVIDER_SCOPE_VIOLATION: 'EXPLAINABILITY_PROVIDER_SCOPE_VIOLATION',
  DECISION_REQUIRED: 'EXPLAINABILITY_DECISION_REQUIRED',
  PERSISTENCE_REQUIRED: 'EXPLAINABILITY_PERSISTENCE_REQUIRED',
  PERSISTENCE_UNAVAILABLE: 'EXPLAINABILITY_PERSISTENCE_UNAVAILABLE',
  IDEMPOTENCY_CONFLICT: 'EXPLAINABILITY_IDEMPOTENCY_CONFLICT',
  INTEGRITY_FAILURE: 'EXPLAINABILITY_INTEGRITY_FAILURE',
  NOT_FOUND: 'EXPLAINABILITY_NOT_FOUND',
  PAYLOAD_TOO_LARGE: 'EXPLAINABILITY_PAYLOAD_TOO_LARGE',
  INVALID_EXPLANATION: 'EXPLAINABILITY_INVALID_EXPLANATION',
  IMMUTABLE: 'EXPLAINABILITY_IMMUTABLE',
});

const DEFAULT_CONFIG = Object.freeze({
  requireTenantId: true,
  enforceAirtelProvider: true,
  maxExplanationBytes: 512 * 1024,
  maxDecisionIdLength: 180,
  maxTenantIdLength: 160,
  maxExplanationIdLength: 180,
  maxVersionLength: 100,
  maxTextLength: 4000,
  maxReasonLength: 1500,
  maxFindings: 500,
  maxFeatureContributions: 500,
  maxEvidenceItems: 500,
  maxControls: 200,
  maxCounterfactuals: 100,
  maxUncertaintyItems: 100,
  maxMetadataDepth: 6,
  maxMetadataKeys: 100,
  maxMetadataArray: 100,
  maxMetadataString: 2000,
  storeFeatureValues: false,
  hashSensitiveIdentifiers: true,
  failClosedOnAuditWrite: false,
  integrityMode: 'hash',
});

const SECRET_KEY_PATTERN = /(password|passphrase|secret|token|authorization|cookie|session|otp|pin|cvv|cvc|pan|private.?key|api.?key|access.?key|credential|signature|provider.?payload|raw(request|response))/i;

const IDENTIFIER_KEY_PATTERN = /^(phone|phoneNumber|msisdn|email|nationalId|nin|accountNumber|bankAccount|walletNumber|customerNumber|deviceId|ip|ipAddress)$/i;

const PROTOTYPE_KEYS = new Set([
  '__proto__',
  'prototype',
  'constructor',
]);

function isPlainObject(value) {
  if (value === null || typeof value !== 'object') return false;

  const proto = Object.getPrototypeOf(value);

  return proto === Object.prototype || proto === null;
}

function normalizeString(value, maxLength = 240) {
  if (value === undefined || value === null) return undefined;

  const normalized = String(value).trim();

  if (!normalized) return undefined;

  return normalized.length > maxLength
    ? normalized.slice(0, maxLength)
    : normalized;
}

function upper(value, maxLength = 120) {
  return normalizeString(value, maxLength)?.toUpperCase();
}

function nowIso(clock) {
  const raw = typeof clock === 'function'
    ? clock()
    : clock?.now?.() ?? Date.now();

  const date =
    raw instanceof Date
      ? new Date(raw.getTime())
      : new Date(raw);

  if (Number.isNaN(date.getTime())) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_INPUT,
      'Clock returned an invalid timestamp.',
    );
  }

  return date.toISOString();
}

function stableNormalize(
  value,
  seen = new WeakSet(),
) {
  if (value === undefined) return null;
  if (value === null) return null;

  if (
    typeof value === 'string'
    || typeof value === 'boolean'
  ) {
    return value;
  }

  if (typeof value === 'bigint') {
    return `${value.toString()}n`;
  }

  if (typeof value === 'number') {
    if (!Number.isFinite(value)) {
      return String(value);
    }

    if (Object.is(value, -0)) {
      return 0;
    }

    return value;
  }

  if (value instanceof Date) {
    return value.toISOString();
  }

  if (Buffer.isBuffer(value)) {
    return `base64:${value.toString('base64')}`;
  }

  if (value instanceof Uint8Array) {
    return `base64:${Buffer.from(value).toString('base64')}`;
  }

  if (
    typeof value === 'function'
    || typeof value === 'symbol'
  ) {
    return String(value);
  }

  if (seen.has(value)) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_INPUT,
      'Circular explanation data is not supported.',
    );
  }

  seen.add(value);

  if (Array.isArray(value)) {
    const output = value.map(
      (item) =>
        stableNormalize(
          item,
          seen,
        ),
    );

    seen.delete(value);

    return output;
  }

  if (
    typeof value.toJSON === 'function'
    && !isPlainObject(value)
  ) {
    const output =
      stableNormalize(
        value.toJSON(),
        seen,
      );

    seen.delete(value);

    return output;
  }

  const output = {};

  for (
    const key of Object.keys(value).sort()
  ) {
    if (PROTOTYPE_KEYS.has(key)) {
      continue;
    }

    output[key] =
      stableNormalize(
        value[key],
        seen,
      );
  }

  seen.delete(value);

  return output;
}

function canonicalize(value) {
  return JSON.stringify(
    stableNormalize(value),
  );
}

function sha256(value) {
  return createHash(
    HASH_ALGORITHM,
  )
    .update(
      canonicalize(value),
    )
    .digest('hex');
}

function hmacSha256(
  secret,
  value,
) {
  return createHmac(
    HASH_ALGORITHM,
    secret,
  )
    .update(
      canonicalize(value),
    )
    .digest('hex');
}

function clone(value) {
  if (value === undefined) {
    return undefined;
  }

  return JSON.parse(
    JSON.stringify(value),
  );
}

function deepFreeze(
  value,
  seen = new WeakSet(),
) {
  if (
    !value
    || typeof value !== 'object'
    || seen.has(value)
  ) {
    return value;
  }

  seen.add(value);

  for (
    const child of Object.values(value)
  ) {
    deepFreeze(
      child,
      seen,
    );
  }

  return Object.freeze(value);
}

function digestValue(value) {
  return `sha256:${sha256(value).slice(0, 40)}`;
}

function redactObject(
  value,
  path = '',
  depth = 0,
  config = DEFAULT_CONFIG,
) {
  if (
    depth > config.maxMetadataDepth
  ) {
    return '[TRUNCATED]';
  }

  if (
    value === undefined
    || value === null
  ) {
    return value;
  }

  if (typeof value === 'string') {
    return value.length > config.maxMetadataString
      ? `${value.slice(0, config.maxMetadataString)}…`
      : value;
  }

  if (typeof value !== 'object') {
    return value;
  }

  if (value instanceof Date) {
    return value.toISOString();
  }

  if (Buffer.isBuffer(value)) {
    return '[BUFFER_REDACTED]';
  }

  if (Array.isArray(value)) {
    return value
      .slice(
        0,
        config.maxMetadataArray,
      )
      .map(
        (item, index) =>
          redactObject(
            item,
            `${path}[${index}]`,
            depth + 1,
            config,
          ),
      );
  }

  const output = {};

  for (
    const key of Object.keys(value)
      .slice(
        0,
        config.maxMetadataKeys,
      )
  ) {
    if (PROTOTYPE_KEYS.has(key)) {
      continue;
    }

    const childPath =
      path
        ? `${path}.${key}`
        : key;

    if (
      SECRET_KEY_PATTERN.test(key)
      || SECRET_KEY_PATTERN.test(childPath)
    ) {
      output[key] =
        '[REDACTED]';

      continue;
    }

    if (
      config.hashSensitiveIdentifiers
      && IDENTIFIER_KEY_PATTERN.test(key)
    ) {
      output[key] =
        digestValue(
          value[key],
        );

      continue;
    }

    output[key] =
      redactObject(
        value[key],
        childPath,
        depth + 1,
        config,
      );
  }

  return output;
}

function safeText(
  value,
  maxLength = 4000,
) {
  return normalizeString(
    value,
    maxLength,
  );
}

function normalizeActor(
  actor,
  config,
) {
  if (!actor) {
    return undefined;
  }

  if (!isPlainObject(actor)) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_INPUT,
      'actor must be an object.',
    );
  }

  const actorId =
    normalizeString(
      actor.actorId
        ?? actor.userId
        ?? actor.principalId
        ?? actor.id,
      180,
    );

  if (!actorId) {
    return undefined;
  }

  return {
    actorId,

    role:
      upper(
        actor.role
          ?? actor.actorRole
          ?? actor.type,
        100,
      ),

    tenantId:
      normalizeString(
        actor.tenantId,
        config.maxTenantIdLength,
      ),

    source:
      normalizeString(
        actor.source
          ?? actor.authSource,
        120,
      ),
  };
}

function normalizeOutcome(value) {
  const candidate =
    upper(
      value,
      80,
    );

  if (!candidate) {
    return EXPLANATION_OUTCOMES.INDETERMINATE;
  }

  const aliases = {
    REVIEW:
      EXPLANATION_OUTCOMES.REQUIRE_REVIEW,

    REQUIRE_REVIEW:
      EXPLANATION_OUTCOMES.REQUIRE_REVIEW,

    APPROVAL_REQUIRED:
      EXPLANATION_OUTCOMES.REQUIRE_APPROVAL,

    REQUIRE_APPROVAL:
      EXPLANATION_OUTCOMES.REQUIRE_APPROVAL,

    DENY:
      EXPLANATION_OUTCOMES.BLOCK,

    DENIED:
      EXPLANATION_OUTCOMES.BLOCK,

    REJECT:
      EXPLANATION_OUTCOMES.BLOCK,

    REJECTED:
      EXPLANATION_OUTCOMES.BLOCK,

    BLOCKED:
      EXPLANATION_OUTCOMES.BLOCK,
  };

  return aliases[candidate]
    ?? candidate;
}

function normalizeSignificance(value) {
  const candidate =
    upper(
      value,
      30,
    )
      ?? SIGNIFICANCE_LEVELS.MEDIUM;

  return Object.values(
    SIGNIFICANCE_LEVELS,
  ).includes(candidate)
    ? candidate
    : SIGNIFICANCE_LEVELS.MEDIUM;
}

function normalizeDirection(value) {
  const candidate =
    upper(
      value,
      30,
    )
      ?? CONTRIBUTION_DIRECTIONS.UNKNOWN;

  return Object.values(
    CONTRIBUTION_DIRECTIONS,
  ).includes(candidate)
    ? candidate
    : CONTRIBUTION_DIRECTIONS.UNKNOWN;
}

function normalizeUncertaintyType(value) {
  const candidate =
    upper(
      value,
      60,
    )
      ?? UNCERTAINTY_TYPES.NONE;

  return Object.values(
    UNCERTAINTY_TYPES,
  ).includes(candidate)
    ? candidate
    : UNCERTAINTY_TYPES.ENGINE_ERROR;
}

function normalizeConfidence(value) {
  if (
    value === undefined
    || value === null
  ) {
    return null;
  }

  const number =
    Number(value);

  if (!Number.isFinite(number)) {
    return null;
  }

  return Number(
    Math.min(
      1,
      Math.max(
        0,
        number,
      ),
    ).toFixed(6),
  );
}

function normalizePercent(value) {
  if (
    value === undefined
    || value === null
  ) {
    return null;
  }

  const number =
    Number(value);

  if (!Number.isFinite(number)) {
    return null;
  }

  return Number(
    Math.min(
      100,
      Math.max(
        -100,
        number,
      ),
    ).toFixed(6),
  );
}

function normalizeFeatureContribution(
  feature,
  config,
  index,
) {
  if (!isPlainObject(feature)) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_EXPLANATION,
      `featureContributions[${index}] must be an object.`,
    );
  }

  const key =
    normalizeString(
      feature.feature
        ?? feature.featureName
        ?? feature.key
        ?? feature.name,
      240,
    );

  if (!key) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_EXPLANATION,
      `featureContributions[${index}] requires a feature name.`,
    );
  }

  const contribution =
    normalizePercent(
      feature.contribution
        ?? feature.impact
        ?? feature.weight,
    );

  const safeDisplayValue =
    config.storeFeatureValues
      ? safeText(
          feature.displayValue
            ?? feature.safeValue,
          500,
        )
      : undefined;

  return {
    feature: key,

    contribution,

    direction:
      normalizeDirection(
        feature.direction,
      ),

    significance:
      normalizeSignificance(
        feature.significance,
      ),

    rank:
      Number.isInteger(feature.rank)
        ? feature.rank
        : index + 1,

    valueDigest:
      feature.valueDigest
        ?? (
          feature.rawValue !== undefined
            ? digestValue(
                feature.rawValue,
              )
            : null
        ),

    displayValue:
      safeDisplayValue
      ?? null,

    evidenceReference:
      normalizeString(
        feature.evidenceReference
          ?? feature.evidenceRef,
        240,
      ),

    source:
      normalizeString(
        feature.source,
        160,
      ),

    description:
      safeText(
        feature.description,
        config.maxReasonLength,
      ),
  };
}

function normalizeFinding(
  finding,
  config,
  index,
) {
  if (!isPlainObject(finding)) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_EXPLANATION,
      `findings[${index}] must be an object.`,
    );
  }

  return {
    code:
      upper(
        finding.code
          ?? finding.reasonCode
          ?? `FINDING_${index + 1}`,
        180,
      ),

    ruleId:
      normalizeString(
        finding.ruleId,
        220,
      ),

    ruleVersion:
      normalizeString(
        finding.ruleVersion,
        config.maxVersionLength,
      ),

    title:
      safeText(
        finding.title,
        300,
      ),

    result:
      upper(
        finding.result,
        40,
      ),

    outcome:
      normalizeOutcome(
        finding.outcome
          ?? finding.configuredOutcome,
      ),

    severity:
      upper(
        finding.severity,
        30,
      )
        ?? 'MEDIUM',

    reasonCode:
      upper(
        finding.reasonCode,
        180,
      ),

    message:
      safeText(
        finding.message
          ?? finding.description,
        config.maxReasonLength,
      ),

    explanation:
      safeText(
        finding.explanation
          ?? finding.rationale,
        config.maxReasonLength,
      ),

    evidenceReferences:
      Array.isArray(
        finding.evidenceReferences,
      )
        ? finding.evidenceReferences
            .slice(0, 100)
            .map(
              (item) =>
                normalizeString(
                  item,
                  240,
                ),
            )
            .filter(Boolean)
        : [],

    affectedFeatures:
      Array.isArray(
        finding.affectedFeatures,
      )
        ? finding.affectedFeatures
            .slice(0, 100)
            .map(
              (item) =>
                normalizeString(
                  item,
                  240,
                ),
            )
            .filter(Boolean)
        : [],

    controlCodes:
      Array.isArray(
        finding.controlCodes,
      )
        ? finding.controlCodes
            .slice(0, 100)
            .map(
              (item) =>
                upper(
                  item,
                  120,
                ),
            )
            .filter(Boolean)
        : [],
  };
}

function normalizeEvidenceItem(
  evidence,
  config,
  index,
) {
  if (!isPlainObject(evidence)) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_EXPLANATION,
      `evidence[${index}] must be an object.`,
    );
  }

  return {
    id:
      normalizeString(
        evidence.id
          ?? evidence.referenceId
          ?? evidence.ref,
        240,
      ),

    type:
      upper(
        evidence.type
          ?? 'EVIDENCE',
        80,
      ),

    source:
      safeText(
        evidence.source,
        240,
      ),

    version:
      normalizeString(
        evidence.version,
        config.maxVersionLength,
      ),

    status:
      upper(
        evidence.status,
        60,
      ),

    authoritative:
      evidence.authoritative
      === true,

    fresh:
      evidence.fresh
      !== false,

    stale:
      evidence.stale
      === true,

    present:
      evidence.present
      !== false,

    valueDigest:
      evidence.valueDigest
        ?? (
          evidence.rawValue !== undefined
            ? digestValue(
                evidence.rawValue,
              )
            : null
        ),

    documentDigest:
      normalizeString(
        evidence.documentDigest,
        160,
      ),

    capturedAt:
      evidence.capturedAt
        ? new Date(
            evidence.capturedAt,
          ).toISOString()
        : undefined,

    observedAt:
      evidence.observedAt
        ? new Date(
            evidence.observedAt,
          ).toISOString()
        : undefined,

    description:
      safeText(
        evidence.description,
        config.maxReasonLength,
      ),
  };
}

function normalizeControl(
  control,
  config,
  index,
) {
  if (typeof control === 'string') {
    return {
      code:
        upper(
          control,
          120,
        ),

      description:
        undefined,

      required:
        true,

      source:
        'POLICY',
    };
  }

  if (!isPlainObject(control)) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_EXPLANATION,
      `controls[${index}] must be an object or string.`,
    );
  }

  const code =
    upper(
      control.code
        ?? control.id,
      120,
    );

  if (!code) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_EXPLANATION,
      `controls[${index}] requires code/id.`,
    );
  }

  return {
    code,

    description:
      safeText(
        control.description,
        config.maxReasonLength,
      ),

    required:
      control.required
      !== false,

    source:
      upper(
        control.source
          ?? 'GOVERNANCE',
        80,
      ),
  };
}

function normalizeUncertainty(
  item,
  config,
  index,
) {
  if (typeof item === 'string') {
    return {
      type:
        normalizeUncertaintyType(
          item,
        ),

      severity:
        'MEDIUM',

      code:
        upper(
          item,
          160,
        ),

      message:
        item.slice(
          0,
          config.maxReasonLength,
        ),

      evidenceReferences: [],
    };
  }

  if (!isPlainObject(item)) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_EXPLANATION,
      `uncertainty[${index}] must be an object or string.`,
    );
  }

  return {
    type:
      normalizeUncertaintyType(
        item.type,
      ),

    severity:
      upper(
        item.severity,
        30,
      )
      ?? 'MEDIUM',

    code:
      upper(
        item.code,
        160,
      ),

    message:
      safeText(
        item.message
          ?? item.description,
        config.maxReasonLength,
      ),

    evidenceReferences:
      Array.isArray(
        item.evidenceReferences,
      )
        ? item.evidenceReferences
            .slice(0, 50)
            .map(
              (ref) =>
                normalizeString(
                  ref,
                  240,
                ),
            )
            .filter(Boolean)
        : [],
  };
}

function normalizeCounterfactual(
  item,
  config,
  index,
) {
  if (!isPlainObject(item)) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_EXPLANATION,
      `counterfactuals[${index}] must be an object.`,
    );
  }

  return {
    id:
      normalizeString(
        item.id
          ?? item.referenceId,
        180,
      ),

    description:
      safeText(
        item.description
          ?? item.scenario,
        config.maxReasonLength,
      ),

    currentOutcome:
      normalizeOutcome(
        item.currentOutcome,
      ),

    hypotheticalOutcome:
      normalizeOutcome(
        item.hypotheticalOutcome
          ?? item.outcome,
      ),

    changedFactors:
      Array.isArray(
        item.changedFactors,
      )
        ? item.changedFactors
            .slice(0, 100)
            .map(
              (factor) =>
                normalizeString(
                  factor,
                  240,
                ),
            )
            .filter(Boolean)
        : [],

    caveat:
      safeText(
        item.caveat,
        config.maxReasonLength,
      ),
  };
}

function normalizeProvenance(
  provenance,
  config,
) {
  if (!provenance) {
    return {};
  }

  if (!isPlainObject(provenance)) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_EXPLANATION,
      'provenance must be an object.',
    );
  }

  return {
    policy:
      provenance.policy
        ? {
            packId:
              normalizeString(
                provenance.policy.packId
                  ?? provenance.policy.policyId,
                200,
              ),

            version:
              normalizeString(
                provenance.policy.version
                  ?? provenance.policy.policyVersion,
                config.maxVersionLength,
              ),

            fingerprint:
              normalizeString(
                provenance.policy.fingerprint
                  ?? provenance.policy.policyFingerprint,
                180,
              ),

            authority:
              safeText(
                provenance.policy.authority,
                240,
              ),
          }
        : null,

    model:
      provenance.model
        ? {
            modelId:
              normalizeString(
                provenance.model.modelId,
                200,
              ),

            version:
              normalizeString(
                provenance.model.version
                  ?? provenance.model.modelVersion,
                config.maxVersionLength,
              ),

            artifactVersion:
              normalizeString(
                provenance.model.artifactVersion,
                120,
              ),

            featureSetVersion:
              normalizeString(
                provenance.model.featureSetVersion,
                120,
              ),

            calibrationVersion:
              normalizeString(
                provenance.model.calibrationVersion,
                120,
              ),

            fingerprint:
              normalizeString(
                provenance.model.fingerprint
                  ?? provenance.model.modelFingerprint,
                180,
              ),

            provider:
              safeText(
                provenance.model.provider,
                160,
              ),

            inferenceMode:
              upper(
                provenance.model.inferenceMode,
                80,
              ),
          }
        : null,

    recommendation:
      provenance.recommendation
        ? {
            engine:
              normalizeString(
                provenance.recommendation.engine,
                180,
              ),

            version:
              normalizeString(
                provenance.recommendation.version,
                config.maxVersionLength,
              ),

            fingerprint:
              normalizeString(
                provenance.recommendation.fingerprint,
                180,
              ),
          }
        : null,

    risk:
      provenance.risk
        ? {
            engine:
              normalizeString(
                provenance.risk.engine,
                180,
              ),

            version:
              normalizeString(
                provenance.risk.version,
                config.maxVersionLength,
              ),

            fingerprint:
              normalizeString(
                provenance.risk.fingerprint,
                180,
              ),
          }
        : null,

    governance:
      provenance.governance
        ? {
            engine:
              normalizeString(
                provenance.governance.engine,
                180,
              ),

            version:
              normalizeString(
                provenance.governance.version,
                config.maxVersionLength,
              ),

            fingerprint:
              normalizeString(
                provenance.governance.fingerprint,
                180,
              ),
          }
        : null,
  };
}

function summarizeStructuredDecision(
  data,
  config,
) {
  const outcome =
    normalizeOutcome(
      data.outcome
        ?? data.decision,
    );

  const firstReason =
    data.reasons?.[0]?.message
    ?? data.reasons?.[0]?.detail
    ?? data.reason
    ?? data.rationale
    ?? data.findings?.[0]?.message
    ?? data.findings?.[0]?.explanation;

  const controls =
    Array.isArray(
      data.controls,
    )
      ? data.controls
          .map(
            (control) =>
              typeof control === 'string'
                ? control
                : control?.code,
          )
          .filter(Boolean)
          .slice(
            0,
            20,
          )
      : [];

  switch (outcome) {
    case EXPLANATION_OUTCOMES.BLOCK:
      return safeText(
        firstReason
          ?? 'The governed operation was blocked by one or more applicable controls.',
        config.maxReasonLength,
      );

    case EXPLANATION_OUTCOMES.REQUIRE_APPROVAL:
      return safeText(
        firstReason
          ?? (
            controls.length
              ? `The operation requires explicit approval and controls: ${controls.join(', ')}.`
              : 'The operation requires explicit approval before execution.'
          ),
        config.maxReasonLength,
      );

    case EXPLANATION_OUTCOMES.REQUIRE_REVIEW:
      return safeText(
        firstReason
          ?? 'The available evidence is insufficient for unattended execution and requires review.',
        config.maxReasonLength,
      );

    case EXPLANATION_OUTCOMES.ALLOW_WITH_CONTROLS:
      return safeText(
        firstReason
          ?? (
            controls.length
              ? `The operation is permitted subject to controls: ${controls.join(', ')}.`
              : 'The operation is permitted subject to governance controls.'
          ),
        config.maxReasonLength,
      );

    case EXPLANATION_OUTCOMES.ALLOW:
      return safeText(
        firstReason
          ?? 'The available policy and governance evidence supports the requested operation.',
        config.maxReasonLength,
      );

    default:
      return safeText(
        firstReason
          ?? 'The decision could not be established with a stronger deterministic explanation.',
        config.maxReasonLength,
      );
  }
}

/**
 * Semantic fingerprint.
 *
 * The explanation ID and timestamps deliberately do not participate in the
 * explanation fingerprint. Those values identify the stored record and the
 * event timing; they are protected separately by integrity verification.
 *
 * This allows a retried request for the same explanation to remain idempotently
 * equivalent even if the caller does not resend server-generated timestamps.
 */
function buildExplanationFingerprint(
  explanation,
) {
  const fingerprintBody = {
    ...clone(explanation),

    explanationId:
      undefined,

    occurredAt:
      undefined,

    recordedAt:
      undefined,

    integrity:
      undefined,

    explanationFingerprint:
      undefined,
  };

  return sha256(
    fingerprintBody,
  );
}

function buildIntegrityValue(
  explanation,
  secret,
  mode,
) {
  const material = {
    explanationFingerprint:
      explanation.explanationFingerprint,

    explanationId:
      explanation.explanationId,

    tenantId:
      explanation.tenantId,

    decisionId:
      explanation.decisionId,

    recordedAt:
      explanation.recordedAt,

    occurredAt:
      explanation.occurredAt,

    schemaVersion:
      explanation.schemaVersion,
  };

  return mode === 'hmac'
    ? hmacSha256(
        secret,
        material,
      )
    : sha256(
        material,
      );
}

function byteSize(value) {
  return Buffer.byteLength(
    canonicalize(value),
    'utf8',
  );
}

export class ExplainabilityStoreError
  extends Error {
  constructor(
    code,
    message,
    details = {},
    options = {},
  ) {
    super(
      message,
      options,
    );

    this.name =
      'ExplainabilityStoreError';

    this.code =
      code;

    this.component =
      COMPONENT;

    this.provider =
      PROVIDER;

    this.details =
      details;

    this.retryable =
      Boolean(
        options.retryable,
      );

    this.httpStatus =
      options.httpStatus
      ?? 400;
  }
}

/**
 * Persistence adapter contract.
 *
 * Required methods:
 *   append(explanation, { idempotencyKey })
 *   findById(tenantId, explanationId)
 *   findByIdempotencyKey(tenantId, idempotencyKey)
 *   findByDecisionId(tenantId, decisionId, options)
 *   listByTenant(tenantId, options)
 *
 * Optional:
 *   healthCheck()
 *   close()
 *
 * append() MUST be append-only. It must reject mutation or replacement of an
 * existing explanation ID. Idempotency is tenant-scoped.
 */
export class InMemoryExplainabilityRepository {
  constructor() {
    this.records =
      new Map();

    this.idempotency =
      new Map();

    this.closed =
      false;
  }

  _assertOpen() {
    if (this.closed) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.PERSISTENCE_UNAVAILABLE,
        'Explainability repository is closed.',
      );
    }
  }

  async append(
    explanation,
    {
      idempotencyKey,
    } = {},
  ) {
    this._assertOpen();

    const recordKey =
      `${explanation.tenantId}:${explanation.explanationId}`;

    const existing =
      this.records.get(
        recordKey,
      );

    if (existing) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.IMMUTABLE,
        'Explainability records are immutable and append-only.',
        {
          explanationId:
            explanation.explanationId,
        },
      );
    }

    if (idempotencyKey) {
      const idemKey =
        `${explanation.tenantId}:${idempotencyKey}`;

      const existingByIdempotency =
        this.idempotency.get(
          idemKey,
        );

      if (existingByIdempotency) {
        if (
          existingByIdempotency.explanationFingerprint
          !== explanation.explanationFingerprint
        ) {
          throw new ExplainabilityStoreError(
            EXPLAINABILITY_ERROR_CODES.IDEMPOTENCY_CONFLICT,
            'Idempotency key is already associated with a different explanation.',
            {
              explanationId:
                existingByIdempotency.explanationId,

              idempotencyKey,
            },
          );
        }

        return clone(
          existingByIdempotency,
        );
      }
    }

    const frozen =
      deepFreeze(
        clone(
          explanation,
        ),
      );

    this.records.set(
      recordKey,
      frozen,
    );

    if (idempotencyKey) {
      this.idempotency.set(
        `${explanation.tenantId}:${idempotencyKey}`,
        frozen,
      );
    }

    return clone(
      frozen,
    );
  }

  async findById(
    tenantId,
    explanationId,
  ) {
    this._assertOpen();

    const record =
      this.records.get(
        `${tenantId}:${explanationId}`,
      );

    return record
      ? clone(record)
      : null;
  }

  async findByIdempotencyKey(
    tenantId,
    idempotencyKey,
  ) {
    this._assertOpen();

    const record =
      this.idempotency.get(
        `${tenantId}:${idempotencyKey}`,
      );

    return record
      ? clone(record)
      : null;
  }

  async findByDecisionId(
    tenantId,
    decisionId,
    options = {},
  ) {
    this._assertOpen();

    const all =
      [...this.records.values()]
        .filter(
          (record) =>
            record.tenantId === tenantId
            && record.decisionId === decisionId,
        )
        .sort(
          (a, b) =>
            new Date(
              a.recordedAt,
            ).getTime()
            -
            new Date(
              b.recordedAt,
            ).getTime(),
        );

    const offset =
      Math.max(
        Number(options.offset) || 0,
        0,
      );

    const limit =
      Math.min(
        Math.max(
          Number(options.limit) || 100,
          1,
        ),
        1000,
      );

    return {
      entries:
        clone(
          all.slice(
            offset,
            offset + limit,
          ),
        ),

      total:
        all.length,

      nextOffset:
        offset + limit < all.length
          ? offset + limit
          : null,
    };
  }

  async listByTenant(
    tenantId,
    options = {},
  ) {
    this._assertOpen();

    let all =
      [...this.records.values()]
        .filter(
          (record) =>
            record.tenantId === tenantId,
        );

    if (options.explanationType) {
      all =
        all.filter(
          (record) =>
            record.explanationType
            === options.explanationType,
        );
    }

    if (options.decisionOutcome) {
      all =
        all.filter(
          (record) =>
            record.decisionOutcome
            === options.decisionOutcome,
        );
    }

    if (options.from) {
      const from =
        new Date(
          options.from,
        ).getTime();

      all =
        all.filter(
          (record) =>
            new Date(
              record.recordedAt,
            ).getTime()
            >= from,
        );
    }

    if (options.to) {
      const to =
        new Date(
          options.to,
        ).getTime();

      all =
        all.filter(
          (record) =>
            new Date(
              record.recordedAt,
            ).getTime()
            <= to,
        );
    }

    all.sort(
      (a, b) =>
        new Date(
          b.recordedAt,
        ).getTime()
        -
        new Date(
          a.recordedAt,
        ).getTime(),
    );

    const offset =
      Math.max(
        Number(options.offset) || 0,
        0,
      );

    const limit =
      Math.min(
        Math.max(
          Number(options.limit) || 100,
          1,
        ),
        1000,
      );

    return {
      entries:
        clone(
          all.slice(
            offset,
            offset + limit,
          ),
        ),

      total:
        all.length,

      nextOffset:
        offset + limit < all.length
          ? offset + limit
          : null,
    };
  }

  async count(
    tenantId,
    options = {},
  ) {
    const result =
      await this.listByTenant(
        tenantId,
        {
          ...options,
          limit:
            1000,
          offset:
            0,
        },
      );

    return result.total;
  }

  async healthCheck() {
    return {
      ok:
        !this.closed,

      durable:
        false,

      type:
        'in-memory',
    };
  }

  async close() {
    this.closed =
      true;

    this.records.clear();
    this.idempotency.clear();
  }
}

export class ExplainabilityStore {
  constructor(options = {}) {
    this.config =
      Object.freeze({
        ...DEFAULT_CONFIG,
        ...(options.config ?? {}),
      });

    this.repository =
      options.repository
      ?? options.store
      ?? null;

    if (!this.repository) {
      if (
        options.allowInMemoryStore
        || process.env.NODE_ENV === 'test'
      ) {
        this.repository =
          new InMemoryExplainabilityRepository();
      } else {
        throw new ExplainabilityStoreError(
          EXPLAINABILITY_ERROR_CODES.PERSISTENCE_REQUIRED,
          'A durable explainability repository is required outside tests/local development.',
          {},
          {
            httpStatus:
              503,
          },
        );
      }
    }

    const requiredMethods = [
      'append',
      'findById',
      'findByIdempotencyKey',
      'findByDecisionId',
      'listByTenant',
    ];

    const missing =
      requiredMethods.filter(
        (method) =>
          typeof this.repository?.[method]
          !== 'function',
      );

    if (missing.length) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.PERSISTENCE_UNAVAILABLE,
        `Explainability repository is missing required methods: ${missing.join(', ')}.`,
        {
          missing,
        },
        {
          httpStatus:
            503,
        },
      );
    }

    if (
      this.config.integrityMode
      === 'hmac'
      && String(
        options.integritySecret ?? '',
      ).length < 32
    ) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.INVALID_INPUT,
        'A minimum 32-character integritySecret is required for HMAC mode.',
        {},
        {
          httpStatus:
            500,
        },
      );
    }

    this.integritySecret =
      options.integritySecret;

    this.clock =
      options.clock
      ?? {
        now:
          () => Date.now(),
      };

    this.idFactory =
      options.idFactory
      ?? (() => randomUUID());

    this.audit =
      options.audit
      ?? null;

    this.logger =
      options.logger
      ?? null;

    this.metrics =
      options.metrics
      ?? null;
  }

  _tenantId(input) {
    const tenantId =
      normalizeString(
        input,
        this.config.maxTenantIdLength,
      );

    if (
      this.config.requireTenantId
      && !tenantId
    ) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.TENANT_REQUIRED,
        'tenantId is required for explainability storage.',
        {},
        {
          httpStatus:
            400,
        },
      );
    }

    return tenantId;
  }

  _decisionId(input) {
    const decisionId =
      normalizeString(
        input,
        this.config.maxDecisionIdLength,
      );

    if (!decisionId) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.DECISION_REQUIRED,
        'decisionId is required for explainability storage.',
        {},
        {
          httpStatus:
            400,
        },
      );
    }

    return decisionId;
  }

  _provider(provider) {
    const normalized =
      upper(
        provider
          ?? PROVIDER,
        40,
      );

    if (
      this.config.enforceAirtelProvider
      && normalized !== PROVIDER
    ) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.PROVIDER_SCOPE_VIOLATION,
        'Explainability store is scoped to Airtel.',
        {
          provider:
            normalized,
        },
        {
          httpStatus:
            409,
        },
      );
    }

    return normalized;
  }

  _normalizeExplanation(input = {}) {
    if (!isPlainObject(input)) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.INVALID_INPUT,
        'Explanation input must be a plain object.',
      );
    }

    const tenantId =
      this._tenantId(
        input.tenantId,
      );

    const decisionId =
      this._decisionId(
        input.decisionId,
      );

    const provider =
      this._provider(
        input.provider,
      );

    const recordedAt =
      input.recordedAt
        ? toIsoSafe(
            input.recordedAt,
          )
        : this._now();

    const occurredAt =
      input.occurredAt
        ? toIsoSafe(
            input.occurredAt,
          )
        : recordedAt;

    const explanationType =
      upper(
        input.explanationType
          ?? EXPLANATION_TYPES.GOVERNANCE_DECISION,
        80,
      );

    if (
      !Object.values(
        EXPLANATION_TYPES,
      ).includes(
        explanationType,
      )
    ) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.INVALID_EXPLANATION,
        `Unsupported explanationType: ${explanationType}.`,
      );
    }

    const decisionOutcome =
      normalizeOutcome(
        input.decisionOutcome
          ?? input.outcome
          ?? input.decision,
      );

    const explanationId =
      normalizeString(
        input.explanationId,
        this.config.maxExplanationIdLength,
      )
      ?? this.idFactory();

    const rawFindings =
      Array.isArray(
        input.findings,
      )
        ? input.findings
        : Array.isArray(
            input.reasons,
          )
          ? input.reasons
          : [];

    const findings =
      rawFindings
        .slice(
          0,
          this.config.maxFindings,
        )
        .map(
          (finding, index) =>
            normalizeFinding(
              finding,
              this.config,
              index,
            ),
        );

    const rawContributions =
      Array.isArray(
        input.featureContributions,
      )
        ? input.featureContributions
        : Array.isArray(
            input.features,
          )
          ? input.features
          : [];

    const featureContributions =
      rawContributions
        .slice(
          0,
          this.config.maxFeatureContributions,
        )
        .map(
          (feature, index) =>
            normalizeFeatureContribution(
              feature,
              this.config,
              index,
            ),
        );

    const evidence =
      (
        Array.isArray(
          input.evidence,
        )
          ? input.evidence
          : []
      )
        .slice(
          0,
          this.config.maxEvidenceItems,
        )
        .map(
          (item, index) =>
            normalizeEvidenceItem(
              item,
              this.config,
              index,
            ),
        );

    const controls =
      (
        Array.isArray(
          input.controls,
        )
          ? input.controls
          : []
      )
        .slice(
          0,
          this.config.maxControls,
        )
        .map(
          (item, index) =>
            normalizeControl(
              item,
              this.config,
              index,
            ),
        );

    const uncertainty =
      (
        Array.isArray(
          input.uncertainty,
        )
          ? input.uncertainty
          : []
      )
        .slice(
          0,
          this.config.maxUncertaintyItems,
        )
        .map(
          (item, index) =>
            normalizeUncertainty(
              item,
              this.config,
              index,
            ),
        );

    const counterfactuals =
      (
        Array.isArray(
          input.counterfactuals,
        )
          ? input.counterfactuals
          : []
      )
        .slice(
          0,
          this.config.maxCounterfactuals,
        )
        .map(
          (item, index) =>
            normalizeCounterfactual(
              item,
              this.config,
              index,
            ),
        );

    const provenance =
      normalizeProvenance(
        input.provenance
          ?? {
            policy:
              input.policy,

            model:
              input.model,

            recommendation:
              input.recommendation,

            risk:
              input.risk,

            governance:
              input.governance,
          },
        this.config,
      );

    const normalizedActor =
      normalizeActor(
        input.actor,
        this.config,
      );

    if (
      normalizedActor?.tenantId
      && tenantId
      && normalizedActor.tenantId
        !== tenantId
    ) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.INVALID_INPUT,
        'actor tenant does not match explanation tenant.',
        {},
        {
          httpStatus:
            409,
        },
      );
    }

    const modelDecision =
      input.modelDecision
      ?? input.predictionDecision;

    const risk =
      isPlainObject(input.risk)
        ? {
            level:
              upper(
                input.risk.level
                  ?? input.risk.riskLevel,
                40,
              ),

            score:
              normalizePercent(
                input.risk.score,
              ),

            confidence:
              normalizeConfidence(
                input.risk.confidence,
              ),

            reasonCodes:
              Array.isArray(
                input.risk.reasonCodes,
              )
                ? input.risk.reasonCodes
                    .slice(
                      0,
                      100,
                    )
                    .map(
                      (code) =>
                        upper(
                          code,
                          160,
                        ),
                    )
                    .filter(Boolean)
                : [],
          }
        : null;

    const policy =
      isPlainObject(input.policy)
        ? {
            decision:
              normalizeOutcome(
                input.policy.decision
                  ?? input.policy.outcome,
              ),

            packId:
              normalizeString(
                input.policy.packId
                  ?? input.policy.policyId,
                200,
              ),

            version:
              normalizeString(
                input.policy.version
                  ?? input.policy.policyVersion,
                this.config.maxVersionLength,
              ),

            fingerprint:
              normalizeString(
                input.policy.fingerprint
                  ?? input.policy.policyFingerprint,
                180,
              ),

            status:
              upper(
                input.policy.status,
                60,
              ),

            authority:
              safeText(
                input.policy.authority,
                240,
              ),
          }
        : null;

    const governance =
      isPlainObject(
        input.governance,
      )
        ? {
            makerCheckerRequired:
              input.governance.makerCheckerRequired
              === true,

            approvalRequired:
              input.governance.approvalRequired
              === true,

            approvalGranted:
              input.governance.approvalGranted
              === true,

            executionAuthorized:
              input.governance.executionAuthorized
              === true,

            fingerprint:
              normalizeString(
                input.governance.fingerprint
                  ?? input.governance.governanceFingerprint,
                180,
              ),

            state:
              upper(
                input.governance.state,
                80,
              ),
          }
        : null;

    const summary =
      safeText(
        input.summary
          ?? input.explanation
          ?? input.rationale
          ?? summarizeStructuredDecision(
            input,
            this.config,
          ),
        this.config.maxReasonLength,
      );

    const decision = {
      action:
        upper(
          input.action,
          120,
        ),

      outcome:
        decisionOutcome,

      confidence:
        normalizeConfidence(
          input.confidence,
        ),

      rationale:
        summary,

      reasonCodes:
        Array.isArray(
          input.reasonCodes,
        )
          ? input.reasonCodes
              .slice(
                0,
                100,
              )
              .map(
                (code) =>
                  upper(
                    code,
                    160,
                  ),
              )
              .filter(Boolean)
          : [],
    };

    const explanation = {
      schemaVersion:
        SCHEMA_VERSION,

      component:
        COMPONENT,

      engine:
        ENGINE_NAME,

      engineVersion:
        ENGINE_VERSION,

      explanationId,

      explanationType,

      provider,

      tenantId,

      decisionId,

      occurredAt,

      recordedAt,

      decisionOutcome,

      decision,

      summary,

      provenance,

      modelDecision:
        modelDecision
          ? {
              decision:
                normalizeOutcome(
                  modelDecision.decision
                    ?? modelDecision.outcome,
                ),

              confidence:
                normalizeConfidence(
                  modelDecision.confidence,
                ),

              modelId:
                normalizeString(
                  modelDecision.modelId,
                  200,
                ),

              modelVersion:
                normalizeString(
                  modelDecision.modelVersion
                    ?? modelDecision.version,
                  this.config.maxVersionLength,
                ),

              fingerprint:
                normalizeString(
                  modelDecision.fingerprint
                    ?? modelDecision.decisionFingerprint,
                  180,
                ),
            }
          : null,

      risk,

      policy,

      governance,

      featureContributions,

      findings,

      evidence,

      controls,

      uncertainty,

      counterfactuals,

      subject: {
        paymentId:
          normalizeString(
            input.subject?.paymentId
              ?? input.paymentId,
            240,
          ),

        transactionId:
          normalizeString(
            input.subject?.transactionId
              ?? input.transactionId,
            240,
          ),

        operation:
          upper(
            input.subject?.operation
              ?? input.operation,
            120,
          ),

        impactLevel:
          upper(
            input.subject?.impactLevel
              ?? input.impactLevel,
            80,
          ),

        currency:
          upper(
            input.subject?.currency
              ?? input.currency,
            20,
          ),

        amountMinorDigest:
          input.subject?.amountMinor
            !== undefined
            ? digestValue(
                input.subject.amountMinor,
              )
            : input.amountMinor
              !== undefined
              ? digestValue(
                  input.amountMinor,
                )
              : null,

        originalIdempotencyKeyDigest:
          input.originalIdempotencyKey
            !== undefined
            ? digestValue(
                input.originalIdempotencyKey,
              )
            : input.subject
                ?.originalIdempotencyKey
              !== undefined
              ? digestValue(
                  input.subject.originalIdempotencyKey,
                )
              : null,

        offlineState:
          upper(
            input.subject?.offlineState
              ?? input.offlineState,
            80,
          ),
      },

      actor:
        normalizedActor,

      metadata:
        redactObject(
          input.metadata
            ?? {},
          'metadata',
          0,
          this.config,
        ),

      safety: {
        rawProviderPayloadStored:
          false,

        secretsStored:
          false,

        credentialsStored:
          false,

        financialMutationPerformed:
          false,

        ledgerMutationPerformed:
          false,

        executionAuthorizationGranted:
          false,

        sourceOfTruth:
          'GOVERNANCE_EVIDENCE_ONLY',
      },
    };

    explanation.explanationFingerprint =
      buildExplanationFingerprint(
        explanation,
      );

    explanation.integrity = {
      algorithm:
        HASH_ALGORITHM,

      mode:
        this.config.integrityMode,

      value:
        buildIntegrityValue(
          explanation,
          this.integritySecret,
          this.config.integrityMode,
        ),
    };

    return explanation;
  }

  async storeExplanation(
    input = {},
    options = {},
  ) {
    const idempotencyKey =
      normalizeString(
        options.idempotencyKey
          ?? input.idempotencyKey,
        300,
      );

    if (!idempotencyKey) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.INVALID_INPUT,
        'idempotencyKey is required for explainability persistence.',
        {},
        {
          httpStatus:
            400,
        },
      );
    }

    /*
     * Resolve tenant before normalization so idempotency remains explicitly
     * tenant-scoped.
     */
    const tenantId =
      this._tenantId(
        input.tenantId,
      );

    const existing =
      await this.repository.findByIdempotencyKey(
        tenantId,
        idempotencyKey,
      );

    const explanation =
      this._normalizeExplanation(
        existing
          ? {
              ...input,
              explanationId:
                existing.explanationId,

              /*
               * Preserve an existing timing envelope when the caller omits
               * timestamps. This keeps a retried logical event stable.
               */
              recordedAt:
                input.recordedAt
                  ?? existing.recordedAt,

              occurredAt:
                input.occurredAt
                  ?? existing.occurredAt,
            }
          : input,
      );

    const size =
      byteSize(
        explanation,
      );

    if (
      size
      > this.config.maxExplanationBytes
    ) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.PAYLOAD_TOO_LARGE,
        'Explanation exceeds the configured maximum payload size.',
        {
          maxBytes:
            this.config.maxExplanationBytes,

          actualBytes:
            size,
        },
        {
          httpStatus:
            413,
        },
      );
    }

    if (existing) {
      if (
        existing.explanationFingerprint
        !== explanation.explanationFingerprint
      ) {
        throw new ExplainabilityStoreError(
          EXPLAINABILITY_ERROR_CODES.IDEMPOTENCY_CONFLICT,
          'The explainability idempotency key refers to a different explanation.',
          {
            idempotencyKey,

            existingExplanationId:
              existing.explanationId,
          },
          {
            httpStatus:
              409,
          },
        );
      }

      return {
        explanation:
          deepFreeze(
            existing,
          ),

        idempotentReplay:
          true,
      };
    }

    let persisted;

    try {
      persisted =
        await this.repository.append(
          explanation,
          {
            idempotencyKey,
          },
        );
    } catch (error) {
      if (
        error?.code
          === EXPLAINABILITY_ERROR_CODES.IDEMPOTENCY_CONFLICT
      ) {
        throw error;
      }

      this._log(
        'error',
        'Explainability persistence failed.',
        {
          tenantId:
            explanation.tenantId,

          decisionId:
            explanation.decisionId,

          error:
            this._safeError(
              error,
            ),
        },
      );

      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.PERSISTENCE_UNAVAILABLE,
        'Explainability persistence failed.',
        {
          decisionId:
            explanation.decisionId,
        },
        {
          retryable:
            true,

          httpStatus:
            503,

          cause:
            error,
        },
      );
    }

    if (
      options.audit
      !== false
    ) {
      try {
        await this._writeAudit(
          persisted,
          {
            idempotencyKey:
              `${idempotencyKey}:audit`,
          },
        );
      } catch (error) {
        if (
          this.config
            .failClosedOnAuditWrite
        ) {
          throw error;
        }
      }
    }

    this._metric(
      'explainability_stored_total',
      {
        explanationType:
          persisted.explanationType,

        outcome:
          persisted.decisionOutcome,
      },
    );

    return {
      explanation:
        deepFreeze(
          persisted,
        ),

      idempotentReplay:
        false,
    };
  }

  async save(
    input = {},
    options = {},
  ) {
    return this.storeExplanation(
      input,
      options,
    );
  }

  async create(
    input = {},
    options = {},
  ) {
    return this.storeExplanation(
      input,
      options,
    );
  }

  buildFromGovernanceResult(
    governanceResult,
    options = {},
  ) {
    if (!isPlainObject(
      governanceResult,
    )) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.INVALID_INPUT,
        'governanceResult must be a plain object.',
      );
    }

    const intelligence =
      governanceResult.intelligence
      ?? {};

    const findings = [
      ...(
        Array.isArray(
          governanceResult.reasons,
        )
          ? governanceResult.reasons.map(
              (reason) => ({
                code:
                  reason.code,

                reasonCode:
                  reason.code,

                severity:
                  reason.severity
                    ?? 'MEDIUM',

                message:
                  reason.message
                    ?? reason.detail,

                outcome:
                  governanceResult.outcome,
              }),
            )
          : []
      ),

      ...(
        Array.isArray(
          governanceResult.findings,
        )
          ? governanceResult.findings
          : []
      ),
    ];

    const controls = [
      ...(
        Array.isArray(
          governanceResult.controls,
        )
          ? governanceResult.controls
          : []
      ),

      ...(
        Array.isArray(
          governanceResult.policy?.controls,
        )
          ? governanceResult.policy.controls
          : []
      ),
    ];

    const uncertainty = [];

    if (
      governanceResult.offline
        ?.unresolved
    ) {
      uncertainty.push({
        type:
          UNCERTAINTY_TYPES.OFFLINE_STATE,

        severity:
          'HIGH',

        code:
          'OFFLINE_STATE_UNRESOLVED',

        message:
          `Execution evidence is unresolved in offline state ${governanceResult.offline.state ?? 'UNKNOWN'}.`,
      });
    }

    if (
      intelligence.policy
        ?.available
      === false
    ) {
      uncertainty.push({
        type:
          UNCERTAINTY_TYPES.POLICY_UNAVAILABLE,

        severity:
          'HIGH',

        code:
          'POLICY_INTELLIGENCE_UNAVAILABLE',

        message:
          'Policy intelligence was unavailable during governance evaluation.',
      });
    }

    if (
      intelligence.prediction
        ?.available
      === false
    ) {
      uncertainty.push({
        type:
          UNCERTAINTY_TYPES.MODEL_UNAVAILABLE,

        severity:
          'MEDIUM',

        code:
          'PREDICTION_SIGNAL_UNAVAILABLE',

        message:
          'Prediction intelligence was unavailable during governance evaluation.',
      });
    }

    if (
      intelligence.risk
        ?.available
      === false
    ) {
      uncertainty.push({
        type:
          UNCERTAINTY_TYPES.ENGINE_ERROR,

        severity:
          'HIGH',

        code:
          'RISK_SIGNAL_UNAVAILABLE',

        message:
          'Risk intelligence was unavailable during governance evaluation.',
      });
    }

    const evidence = [];

    if (
      governanceResult
        .governanceFingerprint
    ) {
      evidence.push({
        id:
          'governance-fingerprint',

        type:
          'GOVERNANCE_FINGERPRINT',

        source:
          ENGINE_NAME,

        status:
          'VERIFIED_REFERENCE',

        authoritative:
          false,

        present:
          true,

        valueDigest:
          `sha256:${String(
            governanceResult
              .governanceFingerprint,
          ).slice(0, 40)}`,

        description:
          'Deterministic fingerprint of the governance context and contributing intelligence signals.',
      });
    }

    if (
      intelligence.policy
        ?.fingerprint
    ) {
      evidence.push({
        id:
          'policy-fingerprint',

        type:
          'POLICY_FINGERPRINT',

        source:
          ENGINE_NAME,

        status:
          'REFERENCE',

        authoritative:
          true,

        present:
          true,

        valueDigest:
          `sha256:${String(
            intelligence
              .policy
              .fingerprint,
          ).slice(0, 40)}`,

        description:
          'Versioned policy fingerprint used in the governance decision.',
      });
    }

    const featureContributions =
      [];

    if (
      Array.isArray(
        options.featureContributions,
      )
    ) {
      featureContributions.push(
        ...options.featureContributions,
      );
    }

    const provenance = {
      governance:
        {
          engine:
            governanceResult.engine
              ?? ENGINE_NAME,

          version:
            governanceResult.engineVersion
              ?? ENGINE_VERSION,

          fingerprint:
            governanceResult
              .governanceFingerprint,
        },

      policy:
        intelligence.policy
          ? {
              packId:
                governanceResult
                  .policy
                  ?.packId,

              version:
                governanceResult
                  .policy
                  ?.version,

              fingerprint:
                intelligence
                  .policy
                  .fingerprint,

              authority:
                governanceResult
                  .policy
                  ?.authority,
            }
          : null,

      model:
        intelligence.prediction
          ? {
              modelId:
                intelligence
                  .prediction
                  .modelId,

              version:
                intelligence
                  .prediction
                  .modelVersion,

              fingerprint:
                intelligence
                  .prediction
                  .fingerprint,
            }
          : null,

      recommendation:
        intelligence.recommendation
          ? {
              engine:
                'airtel-recommendation-engine',

              version:
                undefined,

              fingerprint:
                intelligence
                  .recommendation
                  .fingerprint,
            }
          : null,

      risk:
        intelligence.risk
          ? {
              engine:
                'airtel-risk-engine',

              version:
                undefined,

              fingerprint:
                intelligence
                  .risk
                  .fingerprint,
            }
          : null,
    };

    return this._normalizeExplanation({
      explanationType:
        EXPLANATION_TYPES
          .GOVERNANCE_DECISION,

      tenantId:
        governanceResult.tenantId,

      provider:
        governanceResult.provider
          ?? PROVIDER,

      decisionId:
        governanceResult.decisionId,

      recordedAt:
        governanceResult.evaluatedAt,

      occurredAt:
        governanceResult.evaluatedAt,

      decisionOutcome:
        governanceResult.outcome,

      action:
        governanceResult.action,

      confidence:
        governanceResult.confidence,

      summary:
        governanceResult.summary
          ?? governanceResult.rationale,

      findings,

      controls,

      uncertainty,

      evidence,

      featureContributions,

      provenance,

      policy:
        governanceResult.policy,

      risk:
        governanceResult.risk,

      governance:
        governanceResult.governance,

      modelDecision:
        intelligence.prediction,

      paymentId:
        governanceResult.scope
          ?.paymentId,

      transactionId:
        governanceResult.scope
          ?.transactionId,

      operation:
        governanceResult.operation,

      impactLevel:
        governanceResult.impactLevel,

      currency:
        governanceResult.scope
          ?.currency,

      amountMinor:
        governanceResult.scope
          ?.amountMinor,

      originalIdempotencyKey:
        governanceResult
          .originalIdempotencyKey,

      offlineState:
        governanceResult.offline
          ?.state,

      metadata: {
        governanceOutcome:
          governanceResult.outcome,

        executionState:
          governanceResult
            .executionState,

        policyFingerprint:
          governanceResult
            .policyFingerprint
            ?? intelligence
              .policy
              ?.fingerprint,
      },
    });
  }

  async storeGovernanceExplanation(
    governanceResult,
    options = {},
  ) {
    const explanation =
      this.buildFromGovernanceResult(
        governanceResult,
        options,
      );

    const idempotencyKey =
      normalizeString(
        options.idempotencyKey
          ?? governanceResult.originalIdempotencyKey
          ?? governanceResult.governanceFingerprint
          ?? governanceResult.decisionId,
        300,
      );

    return this.storeExplanation(
      explanation,
      {
        ...options,

        idempotencyKey:
          `governance-explanation:${idempotencyKey}`,
      },
    );
  }

  async getExplanation({
    tenantId,
    explanationId,
  } = {}) {
    const normalizedTenantId =
      this._tenantId(
        tenantId,
      );

    const normalizedExplanationId =
      normalizeString(
        explanationId,
        this.config
          .maxExplanationIdLength,
      );

    if (
      !normalizedExplanationId
    ) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.INVALID_INPUT,
        'explanationId is required.',
      );
    }

    const explanation =
      await this.repository.findById(
        normalizedTenantId,
        normalizedExplanationId,
      );

    if (!explanation) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.NOT_FOUND,
        'Explainability record was not found within the tenant scope.',
        {
          tenantId:
            normalizedTenantId,

          explanationId:
            normalizedExplanationId,
        },
        {
          httpStatus:
            404,
        },
      );
    }

    return deepFreeze(
      explanation,
    );
  }

  async getByDecisionId({
    tenantId,
    decisionId,
    limit = 100,
    offset = 0,
  } = {}) {
    const normalizedTenantId =
      this._tenantId(
        tenantId,
      );

    const normalizedDecisionId =
      this._decisionId(
        decisionId,
      );

    const result =
      await this.repository.findByDecisionId(
        normalizedTenantId,
        normalizedDecisionId,
        {
          limit:
            Math.min(
              Math.max(
                Number(limit) || 100,
                1,
              ),
              1000,
            ),

          offset:
            Math.max(
              Number(offset) || 0,
              0,
            ),
        },
      );

    return {
      ...result,

      entries:
        result.entries.map(
          (entry) =>
            deepFreeze(
              entry,
            ),
        ),
    };
  }

  async listTenant({
    tenantId,
    explanationType,
    decisionOutcome,
    from,
    to,
    limit = 100,
    offset = 0,
  } = {}) {
    const normalizedTenantId =
      this._tenantId(
        tenantId,
      );

    const result =
      await this.repository.listByTenant(
        normalizedTenantId,
        {
          explanationType:
            explanationType
              ? upper(
                  explanationType,
                  80,
                )
              : undefined,

          decisionOutcome:
            decisionOutcome
              ? normalizeOutcome(
                  decisionOutcome,
                )
              : undefined,

          from:
            from
              ? toIsoSafe(from)
              : undefined,

          to:
            to
              ? toIsoSafe(to)
              : undefined,

          limit:
            Math.min(
              Math.max(
                Number(limit) || 100,
                1,
              ),
              1000,
            ),

          offset:
            Math.max(
              Number(offset) || 0,
              0,
            ),
        },
      );

    return {
      ...result,

      entries:
        result.entries.map(
          (entry) =>
            deepFreeze(
              entry,
            ),
        ),
    };
  }

  async verifyExplanation(
    explanation,
  ) {
    if (!isPlainObject(
      explanation,
    )) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.INVALID_EXPLANATION,
        'explanation must be an object.',
      );
    }

    const expectedFingerprint =
      buildExplanationFingerprint(
        explanation,
      );

    const fingerprintMatch =
      expectedFingerprint
      === explanation.explanationFingerprint;

    const expectedIntegrity =
      buildIntegrityValue(
        explanation,
        this.integritySecret,
        explanation.integrity
          ?.mode
          ?? this.config
            .integrityMode,
      );

    const integrityMatch =
      expectedIntegrity
      === explanation.integrity?.value;

    const report = {
      ok:
        fingerprintMatch
        && integrityMatch,

      explanationId:
        explanation.explanationId,

      tenantId:
        explanation.tenantId,

      decisionId:
        explanation.decisionId,

      fingerprintMatch,

      integrityMatch,

      algorithm:
        explanation.integrity?.algorithm
          ?? HASH_ALGORITHM,

      mode:
        explanation.integrity?.mode
          ?? this.config
            .integrityMode,

      expectedFingerprint,

      actualFingerprint:
        explanation.explanationFingerprint,
    };

    if (!report.ok) {
      this._log(
        'error',
        'Explainability integrity verification failed.',
        report,
      );
    }

    return deepFreeze(
      report,
    );
  }

  async verifyStoredExplanation({
    tenantId,
    explanationId,
  } = {}) {
    const explanation =
      await this.getExplanation({
        tenantId,
        explanationId,
      });

    const verification =
      await this.verifyExplanation(
        explanation,
      );

    if (
      !verification.ok
    ) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.INTEGRITY_FAILURE,
        'Stored explanation failed integrity verification.',
        verification,
        {
          httpStatus:
            409,
        },
      );
    }

    return verification;
  }

  async buildEvidenceBundle({
    tenantId,
    decisionId,
  } = {}) {
    const result =
      await this.getByDecisionId({
        tenantId,
        decisionId,
        limit:
          1000,
        offset:
          0,
      });

    const entries = [];
    const verification = [];

    for (
      const entry
      of result.entries
    ) {
      const report =
        await this.verifyExplanation(
          entry,
        );

      entries.push(
        entry,
      );

      verification.push(
        report,
      );
    }

    const bundle = {
      bundleVersion:
        '1.0.0',

      generatedAt:
        this._now(),

      component:
        COMPONENT,

      tenantId:
        this._tenantId(
          tenantId,
        ),

      decisionId:
        this._decisionId(
          decisionId,
        ),

      explanationCount:
        entries.length,

      explanations:
        entries,

      verification,

      safety: {
        financialMutationPerformed:
          false,

        ledgerMutationPerformed:
          false,

        providerCallPerformed:
          false,

        executionAuthorizationGranted:
          false,
      },
    };

    return deepFreeze({
      ...bundle,

      bundleFingerprint:
        sha256(bundle),
    });
  }

  async exportDecisionExplanation({
    tenantId,
    decisionId,
  } = {}) {
    const bundle =
      await this.buildEvidenceBundle({
        tenantId,
        decisionId,
      });

    return JSON.stringify(
      bundle,
      null,
      2,
    );
  }

  _now() {
    return nowIso(
      this.clock,
    );
  }

  async _writeAudit(
    explanation,
    options = {},
  ) {
    if (!this.audit) {
      return null;
    }

    const method =
      this.audit
        .recordDecisionEvent
      ?? this.audit.append
      ?? this.audit.record
      ?? this.audit.write;

    if (
      typeof method
      !== 'function'
    ) {
      throw new ExplainabilityStoreError(
        EXPLAINABILITY_ERROR_CODES.PERSISTENCE_UNAVAILABLE,
        'Configured audit adapter does not expose a supported write method.',
        {},
        {
          retryable:
            true,

          httpStatus:
            503,
        },
      );
    }

    const auditEvent = {
      tenantId:
        explanation.tenantId,

      decisionId:
        explanation.decisionId,

      eventType:
        'GOVERNANCE_EXPLANATION_STORED',

      stage:
        'EXPLAINABILITY',

      outcome:
        explanation.decisionOutcome,

      provider: {
        code:
          PROVIDER,
      },

      request: {
        idempotencyKey:
          options.idempotencyKey
            ?? `explanation:${explanation.explanationId}`,

        source:
          ENGINE_NAME,
      },

      decision: {
        action:
          explanation.decision.action,

        outcome:
          explanation.decisionOutcome,

        confidence:
          explanation.decision.confidence,

        decisionVersion:
          ENGINE_VERSION,

        subjectId:
          explanation.decisionId,
      },

      inputHash:
        explanation.explanationFingerprint,

      outputHash:
        sha256({
          outcome:
            explanation.decisionOutcome,

          summary:
            explanation.summary,

          findings:
            explanation.findings.map(
              (finding) => ({
                code:
                  finding.code,

                result:
                  finding.result,

                outcome:
                  finding.outcome,
              }),
            ),
        }),

      metadata: {
        explanationId:
          explanation.explanationId,

        explanationFingerprint:
          explanation.explanationFingerprint,

        policyFingerprint:
          explanation.policy?.fingerprint
            ?? explanation.provenance
              ?.policy
              ?.fingerprint
            ?? null,

        modelFingerprint:
          explanation.modelDecision?.fingerprint
            ?? explanation.provenance
              ?.model
              ?.fingerprint
            ?? null,

        sizeBytes:
          byteSize(
            explanation,
          ),
      },
    };

    return method.call(
      this.audit,
      auditEvent,
    );
  }

  _log(
    level,
    message,
    context = {},
  ) {
    const method =
      this.logger?.[level]
      ?? this.logger?.info;

    if (
      typeof method
      !== 'function'
    ) {
      return;
    }

    try {
      method.call(
        this.logger,

        redactObject(
          {
            component:
              COMPONENT,

            ...context,
          },

          '',

          0,

          this.config,
        ),

        message,
      );
    } catch {
      /*
       * Observability failures must never alter explainability semantics.
       */
    }
  }

  _metric(
    name,
    labels = {},
  ) {
    try {
      const metric =
        this.metrics?.[name]
        ?? this.metrics?.increment
        ?? this.metrics?.counter;

      if (
        typeof metric
        !== 'function'
      ) {
        return;
      }

      if (
        metric
        === this.metrics?.increment
        ||
        metric
        === this.metrics?.counter
      ) {
        metric.call(
          this.metrics,

          name,

          redactObject(
            labels,
            '',
            0,
            this.config,
          ),
        );
      } else {
        metric.call(
          this.metrics,

          redactObject(
            labels,
            '',
            0,
            this.config,
          ),
        );
      }
    } catch {
      /*
       * Metrics must never affect storage semantics.
       */
    }
  }

  _safeError(error) {
    if (!error) {
      return null;
    }

    return {
      name:
        error.name
          ?? 'Error',

      code:
        error.code
          ?? null,

      message:
        safeText(
          error.message
            ?? 'Unknown error',
          400,
        ),

      retryable:
        Boolean(
          error.retryable,
        ),
    };
  }

  async health() {
    let repository =
      null;

    if (
      typeof this.repository
        ?.healthCheck
      === 'function'
    ) {
      try {
        repository =
          await this.repository.healthCheck();
      } catch (error) {
        repository = {
          ok:
            false,

          error:
            this._safeError(
              error,
            ),
        };
      }
    }

    return deepFreeze({
      component:
        COMPONENT,

      provider:
        PROVIDER,

      version:
        ENGINE_VERSION,

      healthy:
        repository?.ok
        !== false,

      repositoryConfigured:
        Boolean(
          this.repository,
        ),

      auditConfigured:
        Boolean(
          this.audit,
        ),

      integrityMode:
        this.config.integrityMode,

      safety: {
        rawProviderPayloadStored:
          false,

        secretsStored:
          false,

        credentialsStored:
          false,

        financialMutationPerformed:
          false,

        ledgerMutationPerformed:
          false,
      },

      repository,
    });
  }

  async readiness() {
    return this.health();
  }

  getComponentInfo() {
    return Object.freeze({
      component:
        COMPONENT,

      provider:
        PROVIDER,

      version:
        ENGINE_VERSION,

      schemaVersion:
        SCHEMA_VERSION,

      storesRawProviderPayloads:
        false,

      storesSecrets:
        false,

      storesFinancialLedgerEntries:
        false,

      grantsExecutionAuthorization:
        false,

      authoritativeFinancialBoundary:
        'TITECH_FINANCIAL_CORE',
    });
  }
}

function toIsoSafe(value) {
  const date =
    value instanceof Date
      ? new Date(
          value.getTime(),
        )
      : new Date(
          value,
        );

  if (
    Number.isNaN(
      date.getTime(),
    )
  ) {
    throw new ExplainabilityStoreError(
      EXPLAINABILITY_ERROR_CODES.INVALID_INPUT,
      'Invalid date/time value.',
    );
  }

  return date.toISOString();
}

export function createExplainabilityStore(
  options = {},
) {
  return new ExplainabilityStore(
    options,
  );
}

export const createAirtelExplainabilityStore =
  createExplainabilityStore;

export const AirtelPaymentExplainabilityStore =
  ExplainabilityStore;

export default ExplainabilityStore;

export const constants = Object.freeze({
  ENGINE_NAME,
  ENGINE_VERSION,
  COMPONENT,
  PROVIDER,
  SCHEMA_VERSION,
  HASH_ALGORITHM,
});