// investorReportService.js
const PDFDocument = require('pdfkit');
const fs = require('fs');

/**
 * Generate an investor report PDF
 * @param {Object} data - Report data
 * @param {number} data.totalLoans
 * @param {number} data.defaults
 * @param {number} data.activeLoans
 * @param {number} [data.fraudAlerts]
 * @param {number} [data.avgCreditScore]
 * @param {string} [filename="report.pdf"] - Output filename
 * @returns {Promise<string>} Resolves with filename when finished
 */
const generateReport = (data, filename = "report.pdf") => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });

      // Pipe to file
      const stream = fs.createWriteStream(filename);
      doc.pipe(stream);

      // Metadata
      doc.info.Title = "TITech Investor Report";
      doc.info.Author = "TITech Community Capital LTD";

      // Header
      doc.fontSize(22).fillColor('#333').text("TITech Investor Report", { align: 'center' });
      doc.moveDown(2);

      // Summary section
      doc.fontSize(14).fillColor('#000').text(`Date: ${new Date().toLocaleDateString()}`);
      doc.moveDown();

      doc.fontSize(16).text("Portfolio Overview", { underline: true });
      doc.moveDown();

      doc.fontSize(12).list([
        `Total Loans: ${data.totalLoans}`,
        `Defaults: ${data.defaults}`,
        `Active Loans: ${data.activeLoans}`,
        `Fraud Alerts: ${data.fraudAlerts || 0}`,
        `Average Credit Score: ${data.avgCreditScore || 'N/A'}`
      ]);
      doc.moveDown(2);

      // Simple bar chart (using rectangles)
      const chartX = 100;
      const chartY = doc.y;
      const barWidth = 40;
      const scale = 5; // adjust scaling factor

      const bars = [
        { label: 'Loans', value: data.totalLoans, color: '#2196F3' },
        { label: 'Defaults', value: data.defaults, color: '#F44336' },
        { label: 'Active', value: data.activeLoans, color: '#4CAF50' }
      ];

      bars.forEach((bar, i) => {
        const x = chartX + i * (barWidth + 30);
        const height = bar.value * scale;
        doc.fillColor(bar.color).rect(x, chartY, barWidth, -height).fill();
        doc.fillColor('#000').fontSize(10).text(bar.label, x, chartY + 5, { width: barWidth, align: 'center' });
      });

      doc.moveDown(4);

      // Footer
      doc.fontSize(10).fillColor('#666').text("Generated by TITech Community Capital LTD", { align: 'center' });

      doc.end();

      stream.on('finish', () => resolve(filename));
      stream.on('error', reject);
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = { generateReport };
