'use strict';

module.exports = Object.freeze({
  INTERNAL_ERROR: 'ERR_INTERNAL',
  NOT_FOUND: 'ERR_NOT_FOUND',
  VALIDATION_ERROR: 'ERR_VALIDATION',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  FORBIDDEN: 'ERR_FORBIDDEN',
  INSUFFICIENT_BALANCE: 'ERR_INSUFFICIENT_BALANCE',
  WALLET_NOT_FOUND: 'ERR_WALLET_NOT_FOUND',
  TRANSACTION_FAILED: 'ERR_TRANSACTION_FAILED',
  DUPLICATE_TRANSACTION: 'ERR_DUPLICATE_TRANSACTION',
  MOMO_FAILED: 'ERR_MOMO_FAILED',
  FRAUD_DETECTED: 'ERR_FRAUD_FLAGGED',
});