/**

* ============================================================================
* TITech Community Capital Ltd
* Enterprise Legal Audit Event Domain Model
* ============================================================================
*
* File:
* backend/legal/models/LegalAuditEvent.js
*
* Version:
* 2.0.0
*
* Purpose:
* Canonical backend domain model for immutable legal/compliance audit
* events generated by the TITech Community Capital legal subsystem.
*
* Responsibilities:
* ✓ Define the canonical legal audit-event contract
* ✓ Normalize audit event data
* ✓ Validate event identity and lifecycle information
* ✓ Support legal document version traceability
* ✓ Support legal acceptance/revocation/audit workflows
* ✓ Support multi-tenant audit isolation
* ✓ Preserve request/correlation/idempotency context
* ✓ Preserve actor and subject information
* ✓ Support document integrity hashes
* ✓ Provide persistence-safe serialization
* ✓ Provide sanitized API serialization
* ✓ Support MongoDB/Mongoose repositories
* ✓ Support event-driven architecture
* ✓ Support compliance and forensic investigations
*
* Non-responsibilities:
* ✗ Database persistence
* ✗ HTTP/API handling
* ✗ Authentication
* ✗ Authorization
* ✗ Logging transport
* ✗ Queue management
* ✗ React/frontend behavior
* ✗ Legal interpretation
*
* SECURITY PRINCIPLE:
* A legal audit event is evidence of an application event. Once persisted,
* it should be treated as append-only and immutable.
*
* Controllers/services must derive security-sensitive fields such as actor
* identity, tenant identity, IP address, user-agent and timestamps from
* trusted server-side context.
*
* BRAND:
* TITech Community Capital
*
* LEGACY TERMINOLOGY:
* ACFOS must not be used in this module.
*
* ============================================================================
  */

'use strict';

/* ============================================================================

* CONSTANTS
* ========================================================================== */

/**

* Domain model version.
  */
  const LEGAL_AUDIT_EVENT_MODEL_VERSION = '2.0.0';

/**

* Persistence schema version.
*
* Increment when the persisted event structure changes incompatibly.
  */
  const LEGAL_AUDIT_EVENT_SCHEMA_VERSION = 1;

/**

* Legal audit event categories.
  */
  const LEGAL_AUDIT_EVENT_CATEGORIES = Object.freeze({
  DOCUMENT: 'document',
  ACCEPTANCE: 'acceptance',
  PUBLICATION: 'publication',
  VERSION: 'version',
  CONSENT: 'consent',
  POLICY: 'policy',
  PRIVACY: 'privacy',
  TERMS: 'terms',
  DISCLAIMER: 'disclaimer',
  SECURITY: 'security',
  ADMINISTRATION: 'administration',
  SYSTEM: 'system',
  });

/**

* Canonical legal audit actions.
  */
  const LEGAL_AUDIT_ACTIONS = Object.freeze({
  CREATED: 'created',
  VIEWED: 'viewed',
  DOWNLOADED: 'downloaded',

PUBLISHED: 'published',
UNPUBLISHED: 'unpublished',

ACCEPTED: 'accepted',
DECLINED: 'declined',
WITHDRAWN: 'withdrawn',

UPDATED: 'updated',
VERSIONED: 'versioned',
ARCHIVED: 'archived',
RESTORED: 'restored',

EXPORTED: 'exported',

CREATED_DRAFT: 'created_draft',
SUBMITTED_FOR_REVIEW: 'submitted_for_review',
APPROVED: 'approved',
REJECTED: 'rejected',

RETENTION_APPLIED: 'retention_applied',
RETENTION_EXPIRED: 'retention_expired',

ACCESS_GRANTED: 'access_granted',
ACCESS_DENIED: 'access_denied',

VALIDATION_FAILED: 'validation_failed',

SYSTEM_EVENT: 'system_event',
});

/**

* Audit event outcomes.
  */
  const LEGAL_AUDIT_OUTCOMES = Object.freeze({
  SUCCESS: 'success',
  FAILURE: 'failure',
  DENIED: 'denied',
  PENDING: 'pending',
  });

/**

* Actor types.
  */
  const LEGAL_AUDIT_ACTOR_TYPES = Object.freeze({
  USER: 'user',
  ADMIN: 'admin',
  SYSTEM: 'system',
  SERVICE: 'service',
  API_CLIENT: 'api_client',
  ANONYMOUS: 'anonymous',
  });

/**

* Subject types.
  */
  const LEGAL_AUDIT_SUBJECT_TYPES = Object.freeze({
  USER: 'user',
  TENANT: 'tenant',
  ORGANIZATION: 'organization',
  LEGAL_DOCUMENT: 'legal_document',
  LEGAL_ACCEPTANCE: 'legal_acceptance',
  SYSTEM: 'system',
  });

/**

* Audit event sources.
  */
  const LEGAL_AUDIT_SOURCES = Object.freeze({
  WEB: 'web',
  MOBILE_WEB: 'mobile_web',
  MOBILE_APP: 'mobile_app',
  API: 'api',
  ADMIN: 'admin',
  BACKGROUND_JOB: 'background_job',
  SYSTEM: 'system',
  IMPORT: 'import',
  });

/**

* Audit severity.
  */
  const LEGAL_AUDIT_SEVERITY = Object.freeze({
  INFO: 'info',
  NOTICE: 'notice',
  WARNING: 'warning',
  HIGH: 'high',
  CRITICAL: 'critical',
  });

/**

* Required canonical fields.
  */
  const REQUIRED_FIELDS = Object.freeze([
  'eventId',
  'eventType',
  'category',
  'action',
  'outcome',
  'occurredAt',
  ]);

/**

* Field length limits.
*
* These limits protect the backend from unexpectedly large audit payloads.
  */
  const FIELD_LIMITS = Object.freeze({
  eventId: 128,
  eventType: 128,
  category: 64,
  action: 128,
  outcome: 64,
  severity: 32,

documentId: 128,
documentSlug: 256,
documentTitle: 512,
documentVersion: 128,

acceptanceId: 128,

actorId: 128,
actorType: 64,
actorName: 256,

subjectId: 128,
subjectType: 64,

tenantId: 128,
organizationId: 128,

requestId: 256,
correlationId: 256,
traceId: 256,
sessionId: 256,
idempotencyKey: 256,

source: 64,
service: 128,
route: 512,
method: 32,

ipAddress: 128,
userAgent: 2048,

locale: 32,
timezone: 128,

documentHash: 256,
previousEventHash: 256,
eventHash: 256,

reason: 2048,
message: 4096,
});

/* ============================================================================

* INTERNAL HELPERS
* ========================================================================== */

/**

* Determine whether a value is a non-empty string.
*
* @param {*} value
* @returns {boolean}
  */
  function isNonEmptyString(value) {
  return (
  typeof value === 'string' &&
  value.trim().length > 0
  );
  }

/**

* Normalize a string.
*
* @param {*} value
* @param {number} maxLength
* @returns {string|undefined}
  */
  function normalizeString(value, maxLength) {
  if (!isNonEmptyString(value)) {
  return undefined;
  }

const normalized =
value.trim();

if (
Number.isInteger(maxLength) &&
normalized.length > maxLength
) {
return normalized.slice(
0,
maxLength
);
}

return normalized;
}

/**

* Normalize a timestamp to UTC ISO-8601.
*
* @param {*} value
* @returns {string|undefined}
  */
  function normalizeDate(value) {
  if (
  value === undefined ||
  value === null ||
  value === ''
  ) {
  return undefined;
  }

const date =
value instanceof Date
? value
: new Date(value);

if (Number.isNaN(date.getTime())) {
return undefined;
}

return date.toISOString();
}

/**

* Return a trusted current timestamp.
*
* Services may inject a deterministic timestamp for testing.
*
* @param {*} supplied
* @returns {string}
  */
  function getTimestamp(supplied) {
  return (
  normalizeDate(supplied) ||
  new Date().toISOString()
  );
  }

/**

* Check whether a value belongs to an enum.
*
* @param {*} value
* @param {Object} enumeration
* @returns {boolean}
  */
  function isEnumValue(
  value,
  enumeration
  ) {
  return Object.values(
  enumeration
  ).includes(value);
  }

/**

* Generate a locally unique event ID.
*
* The authoritative persistence layer may replace this with a database ID,
* UUID, ULID or equivalent identifier.
*
* @returns {string}
  */
  function generateEventId() {
  const timestamp =
  Date.now().toString(36);

if (
typeof globalThis !== 'undefined' &&
globalThis.crypto &&
typeof globalThis.crypto.randomUUID ===
'function'
) {
return (
`legal-event-${timestamp}-` +
globalThis.crypto.randomUUID()
);
}

return (
`legal-event-${timestamp}-` +
Math.random()
.toString(36)
.slice(2, 18)
);
}

/**

* Generate a correlation identifier.
*
* @returns {string}
  */
  function generateCorrelationId() {
  const timestamp =
  Date.now().toString(36);

if (
typeof globalThis !== 'undefined' &&
globalThis.crypto &&
typeof globalThis.crypto.randomUUID ===
'function'
) {
return (
`legal-correlation-${timestamp}-` +
globalThis.crypto.randomUUID()
);
}

return (
`legal-correlation-${timestamp}-` +
Math.random()
.toString(36)
.slice(2, 18)
);
}

/**

* Generate a stable-enough local audit identifier.
*
* IMPORTANT:
* This is not a cryptographic event hash.
*
* @returns {string}
  */
  function generateLocalHash() {
  const timestamp =
  Date.now().toString(36);

const random =
Math.random()
.toString(36)
.slice(2, 18);

return (
`pending-${timestamp}-${random}`
);
}

/**

* Convert a potentially ORM-backed object into a plain object.
*
* @param {*} value
* @returns {Object}
  */
  function toPlainObject(value) {
  if (
  !value ||
  typeof value !== 'object'
  ) {
  return {};
  }

if (
typeof value.toObject === 'function'
) {
return value.toObject();
}

if (
typeof value.toJSON === 'function'
) {
return value.toJSON();
}

return {
...value,
};
}

/**

* Create a structured validation error.
*
* @param {string} message
* @param {string[]} errors
* @returns {Error}
  */
  function createValidationError(
  message,
  errors = []
  ) {
  const error =
  new Error(message);

error.name =
'LegalAuditEventValidationError';

error.code =
'LEGAL_AUDIT_EVENT_VALIDATION_ERROR';

error.errors =
Object.freeze([
...errors,
]);

return error;
}

/* ============================================================================

* LEGAL AUDIT EVENT DOMAIN MODEL
* ========================================================================== */

class LegalAuditEvent {
/**

* Create a legal audit event.
*
* @param {Object} input
* @param {Object} options
  */
  constructor(
  input = {},
  options = {}
  ) {
  if (
  !input ||
  typeof input !== 'object'
  ) {
  throw new TypeError(
  'LegalAuditEvent requires an object.'
  );
  }


const occurredAt =



  getTimestamp(
    options.occurredAt ||
    input.occurredAt
  );

this.schemaVersion =
  Number.isInteger(
    input.schemaVersion
  )
    ? input.schemaVersion
    : LEGAL_AUDIT_EVENT_SCHEMA_VERSION;

this.modelVersion =
  normalizeString(
    input.modelVersion,
    FIELD_LIMITS.eventType
  ) ||
  LEGAL_AUDIT_EVENT_MODEL_VERSION;

this.eventId =
  normalizeString(
    input.eventId,
    FIELD_LIMITS.eventId
  ) ||
  generateEventId();

this.eventType =
  normalizeString(
    input.eventType,
    FIELD_LIMITS.eventType
  ) ||
  'legal.audit';

this.category =
  normalizeString(
    input.category,
    FIELD_LIMITS.category
  ) ||
  LEGAL_AUDIT_EVENT_CATEGORIES.SYSTEM;

this.action =
  normalizeString(
    input.action,
    FIELD_LIMITS.action
  ) ||
  LEGAL_AUDIT_ACTIONS.SYSTEM_EVENT;

this.outcome =
  normalizeString(
    input.outcome,
    FIELD_LIMITS.outcome
  ) ||
  LEGAL_AUDIT_OUTCOMES.SUCCESS;

this.severity =
  normalizeString(
    input.severity,
    FIELD_LIMITS.severity
  ) ||
  LEGAL_AUDIT_SEVERITY.INFO;

/*
 * Legal document identity.
 */
this.documentId =
  normalizeString(
    input.documentId,
    FIELD_LIMITS.documentId
  );

this.documentSlug =
  normalizeString(
    input.documentSlug,
    FIELD_LIMITS.documentSlug
  );

this.documentTitle =
  normalizeString(
    input.documentTitle,
    FIELD_LIMITS.documentTitle
  );

this.documentVersion =
  normalizeString(
    input.documentVersion,
    FIELD_LIMITS.documentVersion
  );

/*
 * Acceptance correlation.
 */
this.acceptanceId =
  normalizeString(
    input.acceptanceId,
    FIELD_LIMITS.acceptanceId
  );

/*
 * Actor information.
 */
this.actorId =
  normalizeString(
    input.actorId,
    FIELD_LIMITS.actorId
  );

this.actorType =
  normalizeString(
    input.actorType,
    FIELD_LIMITS.actorType
  ) ||
  LEGAL_AUDIT_ACTOR_TYPES.SYSTEM;

this.actorName =
  normalizeString(
    input.actorName,
    FIELD_LIMITS.actorName
  );

/*
 * Subject information.
 */
this.subjectId =
  normalizeString(
    input.subjectId,
    FIELD_LIMITS.subjectId
  );

this.subjectType =
  normalizeString(
    input.subjectType,
    FIELD_LIMITS.subjectType
  ) ||
  LEGAL_AUDIT_SUBJECT_TYPES.LEGAL_DOCUMENT;

/*
 * Multi-tenant context.
 */
this.tenantId =
  normalizeString(
    input.tenantId,
    FIELD_LIMITS.tenantId
  );

this.organizationId =
  normalizeString(
    input.organizationId,
    FIELD_LIMITS.organizationId
  );

/*
 * Distributed tracing / request context.
 */
this.requestId =
  normalizeString(
    input.requestId,
    FIELD_LIMITS.requestId
  );

this.correlationId =
  normalizeString(
    input.correlationId,
    FIELD_LIMITS.correlationId
  ) ||
  generateCorrelationId();

this.traceId =
  normalizeString(
    input.traceId,
    FIELD_LIMITS.traceId
  );

this.sessionId =
  normalizeString(
    input.sessionId,
    FIELD_LIMITS.sessionId
  );

this.idempotencyKey =
  normalizeString(
    input.idempotencyKey,
    FIELD_LIMITS.idempotencyKey
  );

/*
 * Execution context.
 */
this.source =
  normalizeString(
    input.source,
    FIELD_LIMITS.source
  ) ||
  LEGAL_AUDIT_SOURCES.SYSTEM;

this.service =
  normalizeString(
    input.service,
    FIELD_LIMITS.service
  ) ||
  'titech-community-capital-legal';

this.route =
  normalizeString(
    input.route,
    FIELD_LIMITS.route
  );

this.method =
  normalizeString(
    input.method,
    FIELD_LIMITS.method
  );

/*
 * Network/device context.
 *
 * These are sensitive audit fields and should never be exposed through
 * public API serialization without explicit authorization.
 */
this.ipAddress =
  normalizeString(
    input.ipAddress,
    FIELD_LIMITS.ipAddress
  );

this.userAgent =
  normalizeString(
    input.userAgent,
    FIELD_LIMITS.userAgent
  );

/*
 * Regional context.
 */
this.locale =
  normalizeString(
    input.locale,
    FIELD_LIMITS.locale
  );

this.timezone =
  normalizeString(
    input.timezone,
    FIELD_LIMITS.timezone
  );

/*
 * Integrity / chain metadata.
 *
 * eventHash should preferably be generated by a dedicated integrity
 * service using a cryptographic algorithm. This domain model does not
 * pretend to provide cryptographic guarantees by itself.
 */
this.documentHash =
  normalizeString(
    input.documentHash,
    FIELD_LIMITS.documentHash
  );

this.previousEventHash =
  normalizeString(
    input.previousEventHash,
    FIELD_LIMITS.previousEventHash
  );

this.eventHash =
  normalizeString(
    input.eventHash,
    FIELD_LIMITS.eventHash
  ) ||
  generateLocalHash();

/*
 * Human-readable diagnostic context.
 */
this.reason =
  normalizeString(
    input.reason,
    FIELD_LIMITS.reason
  );

this.message =
  normalizeString(
    input.message,
    FIELD_LIMITS.message
  );

/*
 * Extensible metadata.
 *
 * Metadata must never contain secrets, authentication tokens, passwords,
 * payment credentials or unnecessary personally identifiable information.
 */
this.metadata =
  input.metadata &&
  typeof input.metadata === 'object'
    ? {
        ...input.metadata,
      }
    : {};

/*
 * Server-controlled lifecycle timestamps.
 */
this.occurredAt =
  occurredAt;

this.createdAt =
  normalizeDate(
    input.createdAt
  ) ||
  occurredAt;

this.updatedAt =
  normalizeDate(
    input.updatedAt
  ) ||
  occurredAt;


}

/* ==========================================================================

* STATIC FACTORIES
* ======================================================================== */

/**

* Create a document-related audit event.
*
* @param {Object} document
* @param {Object} options
* @returns {LegalAuditEvent}
  */
  static forDocument(
  document,
  options = {}
  ) {
  if (
  !document ||
  typeof document !== 'object'
  ) {
  throw new TypeError(
  'LegalAuditEvent.forDocument requires a legal document.'
  );
  }


return new LegalAuditEvent({



  ...options,

  category:
    options.category ||
    LEGAL_AUDIT_EVENT_CATEGORIES.DOCUMENT,

  documentId:
    options.documentId ||
    document.id,

  documentSlug:
    options.documentSlug ||
    document.slug,

  documentTitle:
    options.documentTitle ||
    document.title,

  documentVersion:
    options.documentVersion ||
    document.version,
});


}

/**

* Create an acceptance audit event.
*
* @param {Object} acceptance
* @param {Object} options
* @returns {LegalAuditEvent}
  */
  static forAcceptance(
  acceptance,
  options = {}
  ) {
  if (
  !acceptance ||
  typeof acceptance !== 'object'
  ) {
  throw new TypeError(
  'LegalAuditEvent.forAcceptance requires a legal acceptance record.'
  );
  }


const action =



  options.action ||
  acceptance.action ||
  LEGAL_AUDIT_ACTIONS.ACCEPTED;

const outcome =
  options.outcome ||
  LEGAL_AUDIT_OUTCOMES.SUCCESS;

return new LegalAuditEvent({
  ...options,

  eventType:
    options.eventType ||
    'legal.acceptance',

  category:
    options.category ||
    LEGAL_AUDIT_EVENT_CATEGORIES.ACCEPTANCE,

  action,

  outcome,

  documentId:
    options.documentId ||
    acceptance.documentId,

  documentSlug:
    options.documentSlug ||
    acceptance.documentSlug,

  documentVersion:
    options.documentVersion ||
    acceptance.documentVersion,

  acceptanceId:
    options.acceptanceId ||
    acceptance.id,

  userId:
    options.userId ||
    acceptance.userId,

  tenantId:
    options.tenantId ||
    acceptance.tenantId,

  organizationId:
    options.organizationId ||
    acceptance.organizationId,

  requestId:
    options.requestId ||
    acceptance.requestId,

  correlationId:
    options.correlationId ||
    acceptance.correlationId,

  source:
    options.source ||
    acceptance.source,
});

}

/**

* Hydrate a persisted event.
*
* @param {Object} input
* @returns {LegalAuditEvent}
  */
  static fromJSON(input) {
  return new LegalAuditEvent(
  toPlainObject(input)
  );
  }

/* ==========================================================================

* VALIDATION
* ======================================================================== */

/**

* Validate the event.
*
* @param {Object} options
* @returns {{valid:boolean,errors:string,warnings:string}}
  */
  validate(options = {}) {
  const {
  requireTenant = false,
  requireActor = false,
  requireDocument = false,
  requireRequestContext = false,
  requireIntegrityHash = false,
  } = options;


const errors = [];



const warnings = [];

for (const field of REQUIRED_FIELDS) {
  if (
    !isNonEmptyString(
      this[field]
    )
  ) {
    errors.push(
      `${field} is required.`
    );
  }
}

if (
  !isEnumValue(
    this.category,
    LEGAL_AUDIT_EVENT_CATEGORIES
  )
) {
  errors.push(
    `Unsupported legal audit category: ${this.category}.`
  );
}

if (
  !isEnumValue(
    this.outcome,
    LEGAL_AUDIT_OUTCOMES
  )
) {
  errors.push(
    `Unsupported audit outcome: ${this.outcome}.`
  );
}

if (
  !isEnumValue(
    this.actorType,
    LEGAL_AUDIT_ACTOR_TYPES
  )
) {
  errors.push(
    `Unsupported actor type: ${this.actorType}.`
  );
}

if (
  !isEnumValue(
    this.subjectType,
    LEGAL_AUDIT_SUBJECT_TYPES
  )
) {
  errors.push(
    `Unsupported subject type: ${this.subjectType}.`
  );
}

if (
  !isEnumValue(
    this.source,
    LEGAL_AUDIT_SOURCES
  )
) {
  errors.push(
    `Unsupported audit source: ${this.source}.`
  );
}

if (
  !isEnumValue(
    this.severity,
    LEGAL_AUDIT_SEVERITY
  )
) {
  errors.push(
    `Unsupported audit severity: ${this.severity}.`
  );
}

if (requireTenant) {
  if (!this.tenantId) {
    errors.push(
      'tenantId is required for this audit event.'
    );
  }
}

if (requireActor) {
  if (
    !this.actorId &&
    this.actorType !==
      LEGAL_AUDIT_ACTOR_TYPES.SYSTEM &&
    this.actorType !==
      LEGAL_AUDIT_ACTOR_TYPES.SERVICE
  ) {
    errors.push(
      'actorId is required for a non-system audit event.'
    );
  }
}

if (requireDocument) {
  if (!this.documentId) {
    errors.push(
      'documentId is required for this event.'
    );
  }

  if (!this.documentVersion) {
    errors.push(
      'documentVersion is required for this event.'
    );
  }
}

if (requireRequestContext) {
  if (
    !this.requestId &&
    !this.correlationId &&
    !this.traceId
  ) {
    errors.push(
      'At least one request, correlation or trace identifier is required.'
    );
  }
}

if (
  requireIntegrityHash &&
  !this.eventHash
) {
  errors.push(
    'eventHash is required for integrity-protected audit events.'
  );
}

if (
  this.category ===
    LEGAL_AUDIT_EVENT_CATEGORIES.ACCEPTANCE &&
  !this.acceptanceId
) {
  warnings.push(
    'Acceptance audit event does not reference an acceptanceId.'
  );
}

if (
  this.category ===
    LEGAL_AUDIT_EVENT_CATEGORIES.DOCUMENT &&
  !this.documentId
) {
  warnings.push(
    'Document audit event does not reference documentId.'
  );
}

if (
  !this.previousEventHash &&
  this.eventHash
) {
  warnings.push(
    'Audit event is not linked to a previous event hash.'
  );
}

return {
  valid:
    errors.length === 0,

  errors,

  warnings,
};


}

/**

* Assert that the event is valid.
*
* @param {Object} options
* @returns {LegalAuditEvent}
  */
  assertValid(options = {}) {
  const result =
  this.validate(options);


if (!result.valid) {



  throw createValidationError(
    'Invalid legal audit event.',
    result.errors
  );
}

return this;


}

/* ==========================================================================

* CLASSIFICATION HELPERS
* ======================================================================== */

/**

* Determine whether the event concerns a legal document.
*
* @returns {boolean}
  */
  isDocumentEvent() {
  return (
  this.category ===
  LEGAL_AUDIT_EVENT_CATEGORIES.DOCUMENT
  );
  }

/**

* Determine whether the event concerns legal acceptance.
*
* @returns {boolean}
  */
  isAcceptanceEvent() {
  return (
  this.category ===
  LEGAL_AUDIT_EVENT_CATEGORIES.ACCEPTANCE
  );
  }

/**

* Determine whether the event represents a successful operation.
*
* @returns {boolean}
  */
  isSuccessful() {
  return (
  this.outcome ===
  LEGAL_AUDIT_OUTCOMES.SUCCESS
  );
  }

/**

* Determine whether the event represents a failed operation.
*
* @returns {boolean}
  */
  isFailure() {
  return (
  this.outcome ===
  LEGAL_AUDIT_OUTCOMES.FAILURE
  );
  }

/**

* Determine whether the event represents denied access.
*
* @returns {boolean}
  */
  isDenied() {
  return (
  this.outcome ===
  LEGAL_AUDIT_OUTCOMES.DENIED ||
  this.action ===
  LEGAL_AUDIT_ACTIONS.ACCESS_DENIED
  );
  }

/**

* Determine whether the event should receive elevated monitoring.
*
* @returns {boolean}
  */
  isHighRisk() {
  return (
  this.severity ===
  LEGAL_AUDIT_SEVERITY.HIGH ||
  this.severity ===
  LEGAL_AUDIT_SEVERITY.CRITICAL
  );
  }

/* ==========================================================================

* DOCUMENT HELPERS
* ======================================================================== */

/**

* Check whether this event references a specific document version.
*
* @param {Object} document
* @returns {boolean}
  */
  matchesDocument(document) {
  if (
  !document ||
  typeof document !== 'object'
  ) {
  return false;
  }


return (



  this.documentId === document.id &&
  this.documentSlug === document.slug &&
  this.documentVersion === document.version
);


}

/**

* Check whether this event references the same legal document regardless
* of version.
*
* @param {Object} document
* @returns {boolean}
  */
  matchesDocumentIdentity(document) {
  if (
  !document ||
  typeof document !== 'object'
  ) {
  return false;
  }


return (



  this.documentId === document.id &&
  this.documentSlug === document.slug
);


}

/* ==========================================================================

* SERIALIZATION
* ======================================================================== */

/**

* Full persistence representation.
*
* This representation contains sensitive audit data and must not be sent
* directly to untrusted clients.
*
* @returns {Object}
  */
  toPersistenceObject() {
  return {
  schemaVersion:
  this.schemaVersion,

  modelVersion:
  this.modelVersion,

  eventId:
  this.eventId,

  eventType:
  this.eventType,

  category:
  this.category,

  action:
  this.action,

  outcome:
  this.outcome,

  severity:
  this.severity,

  documentId:
  this.documentId,

  documentSlug:
  this.documentSlug,

  documentTitle:
  this.documentTitle,

  documentVersion:
  this.documentVersion,

  acceptanceId:
  this.acceptanceId,

  actorId:
  this.actorId,

  actorType:
  this.actorType,

  actorName:
  this.actorName,

  subjectId:
  this.subjectId,

  subjectType:
  this.subjectType,

  tenantId:
  this.tenantId,

  organizationId:
  this.organizationId,

  requestId:
  this.requestId,

  correlationId:
  this.correlationId,

  traceId:
  this.traceId,

  sessionId:
  this.sessionId,

  idempotencyKey:
  this.idempotencyKey,

  source:
  this.source,

  service:
  this.service,

  route:
  this.route,

  method:
  this.method,

  ipAddress:
  this.ipAddress,

  userAgent:
  this.userAgent,

  locale:
  this.locale,

  timezone:
  this.timezone,

  documentHash:
  this.documentHash,

  previousEventHash:
  this.previousEventHash,

  eventHash:
  this.eventHash,

  reason:
  this.reason,

  message:
  this.message,

  metadata:
  {
  ...this.metadata,
  },

  occurredAt:
  this.occurredAt,

  createdAt:
  this.createdAt,

  updatedAt:
  this.updatedAt,
  };
  }

/**

* Sanitized API representation.
*
* Sensitive network and infrastructure fields are intentionally excluded.
*
* @returns {Object}
  */
  toPublicObject() {
  return {
  eventId:
  this.eventId,

  eventType:
  this.eventType,

  category:
  this.category,

  action:
  this.action,

  outcome:
  this.outcome,

  severity:
  this.severity,

  documentId:
  this.documentId,

  documentSlug:
  this.documentSlug,

  documentTitle:
  this.documentTitle,

  documentVersion:
  this.documentVersion,

  acceptanceId:
  this.acceptanceId,

  actorType:
  this.actorType,

  subjectType:
  this.subjectType,

  source:
  this.source,

  occurredAt:
  this.occurredAt,

  reason:
  this.reason,

  message:
  this.message,
  };
  }

/**

* Minimal event envelope suitable for queues/event buses.
*
* @returns {Object}
  */
  toEventEnvelope() {
  return {
  eventId:
  this.eventId,

  eventType:
  this.eventType,

  category:
  this.category,

  action:
  this.action,

  outcome:
  this.outcome,

  severity:
  this.severity,

  occurredAt:
  this.occurredAt,

  correlationId:
  this.correlationId,

  traceId:
  this.traceId,

  tenantId:
  this.tenantId,

  documentId:
  this.documentId,

  documentVersion:
  this.documentVersion,
  };
  }

/**

* Return JSON-safe representation.
*
* @returns {Object}
  */
  toJSON() {
  return this.toPersistenceObject();
  }

/**

* Clone the event.
*
* @returns {LegalAuditEvent}
  */
  clone() {
  return new LegalAuditEvent(
  this.toPersistenceObject()
  );
  }
  }

/* ============================================================================

* FUNCTIONAL API
* ========================================================================== */

/**

* Create a legal audit event.
*
* @param {Object} input
* @param {Object} options
* @returns {LegalAuditEvent}
  */
  function createLegalAuditEvent(
  input = {},
  options = {}
  ) {
  return new LegalAuditEvent(
  input,
  options
  );
  }

/**

* Normalize a legal audit event.
*
* @param {Object} input
* @param {Object} options
* @returns {LegalAuditEvent}
  */
  function normalizeLegalAuditEvent(
  input = {},
  options = {}
  ) {
  return new LegalAuditEvent(
  input,
  options
  );
  }

/**

* Validate an audit event without throwing.
*
* @param {Object} input
* @param {Object} options
* @returns {{valid:boolean,errors:string,warnings:string}}
  */
  function validateLegalAuditEvent(
  input = {},
  options = {}
  ) {
  try {
  return new LegalAuditEvent(
  input,
  options
  ).validate(options);
  } catch (error) {
  return {
  valid: false,

  errors: [
  error.message ||
  'Unable to validate legal audit event.',
  ],

  warnings: [],
  };
  }
  }

/**

* Assert that an audit event is valid.
*
* @param {Object} input
* @param {Object} options
* @returns {LegalAuditEvent}
  */
  function assertLegalAuditEvent(
  input = {},
  options = {}
  ) {
  return new LegalAuditEvent(
  input,
  options
  ).assertValid(options);
  }

/* ============================================================================

* COMPARISON / INTEGRITY HELPERS
* ========================================================================== */

/**

* Determine whether two events reference the same event ID.
*
* @param {LegalAuditEvent|Object} left
* @param {LegalAuditEvent|Object} right
* @returns {boolean}
  */
  function isSameAuditEvent(
  left,
  right
  ) {
  if (
  !left ||
  !right
  ) {
  return false;
  }

return (
left.eventId ===
right.eventId
);
}

/**

* Determine whether two events reference the same legal document version.
*
* @param {LegalAuditEvent|Object} left
* @param {LegalAuditEvent|Object} right
* @returns {boolean}
  */
  function isSameDocumentVersion(
  left,
  right
  ) {
  if (
  !left ||
  !right
  ) {
  return false;
  }

return (
left.documentId ===
right.documentId &&
left.documentSlug ===
right.documentSlug &&
left.documentVersion ===
right.documentVersion
);
}

/**

* Determine whether an event can be considered part of the same request
* execution chain.
*
* @param {LegalAuditEvent|Object} left
* @param {LegalAuditEvent|Object} right
* @returns {boolean}
  */
  function isSameCorrelationChain(
  left,
  right
  ) {
  if (
  !left ||
  !right
  ) {
  return false;
  }

return Boolean(
left.correlationId &&
right.correlationId &&
left.correlationId ===
right.correlationId
);
}

/**

* Return an audit-safe summary suitable for operational logging.
*
* Sensitive network/device information is intentionally excluded.
*
* @param {LegalAuditEvent|Object} event
* @returns {Object}
  */
  function getLegalAuditSummary(event) {
  const model =
  event instanceof LegalAuditEvent
  ? event
  : new LegalAuditEvent(event);

return {
eventId:
model.eventId,


eventType:
  model.eventType,

category:
  model.category,

action:
  model.action,

outcome:
  model.outcome,

severity:
  model.severity,

documentId:
  model.documentId,

documentSlug:
  model.documentSlug,

documentVersion:
  model.documentVersion,

acceptanceId:
  model.acceptanceId,

actorId:
  model.actorId,

actorType:
  model.actorType,

subjectId:
  model.subjectId,

subjectType:
  model.subjectType,

tenantId:
  model.tenantId,

organizationId:
  model.organizationId,

requestId:
  model.requestId,

correlationId:
  model.correlationId,

traceId:
  model.traceId,

source:
  model.source,

service:
  model.service,

occurredAt:
  model.occurredAt,


};
}

/* ============================================================================

* MODULE EXPORTS
* ========================================================================== */

module.exports = {
LegalAuditEvent,

LEGAL_AUDIT_EVENT_MODEL_VERSION,

LEGAL_AUDIT_EVENT_SCHEMA_VERSION,

LEGAL_AUDIT_EVENT_CATEGORIES,

LEGAL_AUDIT_ACTIONS,

LEGAL_AUDIT_OUTCOMES,

LEGAL_AUDIT_ACTOR_TYPES,

LEGAL_AUDIT_SUBJECT_TYPES,

LEGAL_AUDIT_SOURCES,

LEGAL_AUDIT_SEVERITY,

REQUIRED_FIELDS,

FIELD_LIMITS,

createLegalAuditEvent,

normalizeLegalAuditEvent,

validateLegalAuditEvent,

assertLegalAuditEvent,

isSameAuditEvent,

isSameDocumentVersion,

isSameCorrelationChain,

getLegalAuditSummary,
};

/**

* ============================================================================
* END OF FILE
* ============================================================================
  */