/**
 * ============================================================================
 * TITech Community Capital
 * Enterprise Legal Utilities
 * ============================================================================
 *
 * File:
 *   frontend/src/legal/legalUtils.js
 *
 * Purpose:
 *   Shared, deterministic utilities for working with TITech Community Capital
 *   legal-document metadata.
 *
 * Architectural principles
 * ----------------------------------------------------------------------------
 * - legalRegistry.js owns document metadata.
 * - legalTypes.js owns validation and normalization rules.
 * - legalUtils.js owns reusable operational helpers.
 * - React components must not duplicate legal-document business logic.
 * - Legal content is never stored or generated by this module.
 * - Frontend validation improves safety but is NOT the authoritative legal
 *   acceptance or compliance system.
 *
 * IMPORTANT
 * ----------------------------------------------------------------------------
 * This module does NOT constitute legal advice, regulatory approval,
 * licensing, authorization or a determination that TITech may legally
 * perform any particular financial activity.
 *
 * The backend must remain authoritative for:
 *   - legal-document versions
 *   - publication state
 *   - effective dates
 *   - acceptance records
 *   - legal audit trails
 *   - tenant applicability
 *   - regulatory compliance
 *
 * ============================================================================
 */

'use strict';

import LEGAL_DOCUMENTS, {
  LEGAL_STATUS,
  LEGAL_PRIORITY,
  LEGAL_ACCEPTANCE_SCOPE,
  getLegalDocumentById,
  getLegalDocumentBySlug,
} from './legalRegistry';

import {
  validateLegalRegistry,
  normalizeLegalDocument,
} from './legalTypes';

/* ============================================================================
 * Constants
 * ========================================================================== */

const DEFAULT_LOCALE = 'en-UG';

const VALID_DATE_FORMAT_OPTIONS = Object.freeze({
  year: 'numeric',
  month: 'long',
  day: 'numeric',
});

/* ============================================================================
 * Internal helpers
 * ========================================================================== */

/**
 * Determine whether a value is a non-empty string.
 */
function isNonEmptyString(value) {
  return (
    typeof value === 'string' &&
    value.trim().length > 0
  );
}

/**
 * Safely normalize an array.
 */
function normalizeArray(value) {
  return Array.isArray(value) ? value : [];
}

/**
 * Safely parse a date.
 *
 * Returns:
 *   Date | null
 *
 * Date-only ISO values such as 2026-01-15 are parsed using the
 * ECMAScript date semantics. For legal display purposes this is generally
 * acceptable because only the calendar date is rendered.
 */
function parseLegalDate(date) {
  if (
    date === null ||
    date === undefined ||
    date === ''
  ) {
    return null;
  }

  if (date instanceof Date) {
    return Number.isNaN(date.getTime())
      ? null
      : date;
  }

  const parsed = new Date(date);

  return Number.isNaN(parsed.getTime())
    ? null
    : parsed;
}

/* ============================================================================
 * Configuration validation
 * ========================================================================== */

/**
 * Validate the complete legal configuration.
 *
 * This should be called during:
 *   - development startup
 *   - automated tests
 *   - CI/CD validation
 *   - pre-production verification
 *
 * The authoritative validation rules live in legalTypes.js.
 */
export function validateLegalConfiguration() {
  return validateLegalRegistry(
    LEGAL_DOCUMENTS
  );
}

/**
 * Validate a single legal document.
 */
export function validateLegalDocument(document) {
  if (!document) {
    return {
      valid: false,
      errors: ['Legal document is required.'],
    };
  }

  try {
    const result = validateLegalRegistry([document]);

    return result;
  } catch (error) {
    return {
      valid: false,
      errors: [
        error?.message ||
          'Unable to validate legal document.',
      ],
    };
  }
}

/* ============================================================================
 * Document normalization
 * ========================================================================== */

/**
 * Normalize a legal document through the canonical legalTypes layer.
 *
 * Falls back to the original document if normalizeLegalDocument is not
 * available in an older legalTypes implementation.
 */
export function normalizeLegalDocumentMetadata(document) {
  if (!document) {
    return null;
  }

  if (typeof normalizeLegalDocument === 'function') {
    return normalizeLegalDocument(document);
  }

  return document;
}

/**
 * Normalize a legal-document version.
 *
 * Examples:
 *   " 1.0.0 " -> "1.0.0"
 *   null       -> null
 *   ""         -> null
 */
export function normalizeLegalVersion(version) {
  if (
    version === null ||
    version === undefined
  ) {
    return null;
  }

  const normalized = String(version).trim();

  return normalized || null;
}

/**
 * Extract the current version from a legal document.
 */
export function getLegalDocumentVersion(document) {
  if (!document) {
    return null;
  }

  return normalizeLegalVersion(
    document.currentVersion
  );
}

/* ============================================================================
 * Document lookup
 * ========================================================================== */

/**
 * Find a legal document by immutable document ID.
 */
export function findLegalDocumentById(id) {
  if (!isNonEmptyString(id)) {
    return null;
  }

  return getLegalDocumentById(id.trim());
}

/**
 * Find a legal document by public slug.
 */
export function findLegalDocumentBySlug(slug) {
  if (!isNonEmptyString(slug)) {
    return null;
  }

  return getLegalDocumentBySlug(slug.trim());
}

/**
 * Resolve a document using either its ID or slug.
 */
export function resolveLegalDocument(identifier) {
  if (!isNonEmptyString(identifier)) {
    return null;
  }

  const normalizedIdentifier =
    identifier.trim();

  return (
    findLegalDocumentById(
      normalizedIdentifier
    ) ||
    findLegalDocumentBySlug(
      normalizedIdentifier
    )
  );
}

/* ============================================================================
 * Publication helpers
 * ========================================================================== */

/**
 * Determine whether a legal document is currently published.
 *
 * A document is considered published only when:
 *   - status === published
 *   - an effective date exists
 */
export function isPublishedDocument(document) {
  return Boolean(
    document &&
    document.status === LEGAL_STATUS.PUBLISHED &&
    isEffectiveDocument(document)
  );
}

/**
 * Determine whether a document is publicly accessible according to its
 * registry metadata and lifecycle.
 */
export function isPublicDocument(document) {
  return Boolean(
    document &&
    document.public === true &&
    [
      LEGAL_STATUS.APPROVED,
      LEGAL_STATUS.SCHEDULED,
      LEGAL_STATUS.PUBLISHED,
    ].includes(document.status)
  );
}

/**
 * Determine whether a document is approved.
 */
export function isApprovedDocument(document) {
  return (
    document?.status ===
    LEGAL_STATUS.APPROVED
  );
}

/**
 * Determine whether a document is scheduled.
 */
export function isScheduledDocument(document) {
  return (
    document?.status ===
    LEGAL_STATUS.SCHEDULED
  );
}

/**
 * Determine whether a document is retired.
 */
export function isRetiredDocument(document) {
  return (
    document?.status ===
    LEGAL_STATUS.RETIRED
  );
}

/**
 * Determine whether a document has been superseded.
 */
export function isSupersededDocument(document) {
  return (
    document?.status ===
    LEGAL_STATUS.SUPERSEDED
  );
}

/**
 * Determine whether a document is a draft/review document.
 */
export function isPrePublicationDocument(document) {
  return Boolean(
    document &&
    [
      LEGAL_STATUS.DRAFT,
      LEGAL_STATUS.REVIEW,
    ].includes(document.status)
  );
}

/* ============================================================================
 * Effective-date helpers
 * ========================================================================== */

/**
 * Determine whether a document has a valid effective date.
 */
export function isEffectiveDocument(
  document,
  referenceDate = new Date()
) {
  if (!document?.effectiveDate) {
    return false;
  }

  const effectiveDate =
    parseLegalDate(
      document.effectiveDate
    );

  if (!effectiveDate) {
    return false;
  }

  const reference =
    parseLegalDate(referenceDate);

  if (!reference) {
    return false;
  }

  return effectiveDate.getTime() <=
    reference.getTime();
}

/**
 * Determine whether a document is scheduled for a future effective date.
 */
export function isFutureEffectiveDocument(
  document,
  referenceDate = new Date()
) {
  if (!document?.effectiveDate) {
    return false;
  }

  const effectiveDate =
    parseLegalDate(
      document.effectiveDate
    );

  const reference =
    parseLegalDate(referenceDate);

  if (!effectiveDate || !reference) {
    return false;
  }

  return effectiveDate.getTime() >
    reference.getTime();
}

/* ============================================================================
 * Acceptance helpers
 * ========================================================================== */

/**
 * Determine whether a document requires acceptance.
 */
export function isAcceptanceRequired(document) {
  return Boolean(
    document?.requiresAcceptance === true
  );
}

/**
 * Determine whether acceptance is required before normal platform use.
 */
export function requiresAcceptanceBeforeUse(
  document
) {
  return Boolean(
    document?.requiresAcceptance === true &&
    document?.acceptanceRequiredBeforeUse === true
  );
}

/**
 * Determine whether acceptance is required before a transaction.
 */
export function requiresAcceptanceBeforeTransaction(
  document
) {
  return Boolean(
    document?.requiresAcceptance === true &&
    document?.acceptanceRequiredBeforeTransaction === true &&
    document?.acceptanceScope ===
      LEGAL_ACCEPTANCE_SCOPE.TRANSACTION
  );
}

/**
 * Determine whether acceptance applies at tenant level.
 */
export function requiresTenantAcceptance(
  document
) {
  return Boolean(
    document?.requiresAcceptance === true &&
    document?.acceptanceScope ===
      LEGAL_ACCEPTANCE_SCOPE.TENANT
  );
}

/**
 * Determine whether acceptance applies at organization level.
 */
export function requiresOrganizationAcceptance(
  document
) {
  return Boolean(
    document?.requiresAcceptance === true &&
    document?.acceptanceScope ===
      LEGAL_ACCEPTANCE_SCOPE.ORGANIZATION
  );
}

/**
 * Determine whether acceptance applies at individual-user level.
 */
export function requiresUserAcceptance(
  document
) {
  return Boolean(
    document?.requiresAcceptance === true &&
    document?.acceptanceScope ===
      LEGAL_ACCEPTANCE_SCOPE.USER
  );
}

/**
 * Determine whether the legal version should be locked when accepted.
 */
export function shouldLockAcceptedVersion(
  document
) {
  return Boolean(
    document?.acceptanceVersionLock !== false
  );
}

/* ============================================================================
 * Document visibility
 * ========================================================================== */

/**
 * Return documents that are safe candidates for the public legal index.
 */
export function getVisiblePublicLegalDocuments() {
  return LEGAL_DOCUMENTS.filter(
    (document) =>
      isPublicDocument(document)
  );
}

/**
 * Return documents currently published and effective.
 */
export function getCurrentLegalDocuments() {
  return LEGAL_DOCUMENTS.filter(
    (document) =>
      isPublishedDocument(document)
  );
}

/**
 * Return critical legal documents.
 */
export function getCriticalLegalDocuments() {
  return LEGAL_DOCUMENTS.filter(
    (document) =>
      document.priority ===
      LEGAL_PRIORITY.CRITICAL
  );
}

/**
 * Return documents requiring acceptance.
 */
export function getDocumentsRequiringAcceptance() {
  return LEGAL_DOCUMENTS.filter(
    (document) =>
      isAcceptanceRequired(document)
  );
}

/**
 * Return transaction-level legal documents.
 */
export function getTransactionLegalDocuments() {
  return LEGAL_DOCUMENTS.filter(
    (document) =>
      requiresAcceptanceBeforeTransaction(
        document
      )
  );
}

/* ============================================================================
 * Search helpers
 * ========================================================================== */

/**
 * Search registry metadata.
 *
 * This searches metadata only.
 * It does NOT search substantive legal content.
 */
export function searchLegalDocuments(
  searchTerm
) {
  if (!isNonEmptyString(searchTerm)) {
    return [];
  }

  const query =
    searchTerm.trim().toLowerCase();

  return LEGAL_DOCUMENTS.filter(
    (document) => {
      const searchableFields = [
        document.id,
        document.slug,
        document.title,
        document.shortTitle,
        document.category,
        document.priority,
        document.jurisdiction,
        ...normalizeArray(
          document.tags
        ),
        ...normalizeArray(
          document.audience
        ),
      ];

      return searchableFields.some(
        (field) =>
          String(field)
            .toLowerCase()
            .includes(query)
      );
    }
  );
}

/* ============================================================================
 * Date formatting
 * ========================================================================== */

/**
 * Format a legal date for user-facing display.
 *
 * Returns an empty string for invalid/missing dates.
 */
export function formatLegalDate(
  date,
  locale = DEFAULT_LOCALE
) {
  const parsed =
    parseLegalDate(date);

  if (!parsed) {
    return '';
  }

  try {
    return new Intl.DateTimeFormat(
      locale,
      VALID_DATE_FORMAT_OPTIONS
    ).format(parsed);
  } catch {
    return new Intl.DateTimeFormat(
      DEFAULT_LOCALE,
      VALID_DATE_FORMAT_OPTIONS
    ).format(parsed);
  }
}

/**
 * Format a document's effective date.
 */
export function formatEffectiveDate(
  document,
  locale = DEFAULT_LOCALE
) {
  return formatLegalDate(
    document?.effectiveDate,
    locale
  );
}

/* ============================================================================
 * Route / API helpers
 * ========================================================================== */

/**
 * Get the frontend route for a legal document.
 */
export function getLegalRoute(document) {
  if (!document?.route) {
    return null;
  }

  return String(
    document.route
  ).trim() || null;
}

/**
 * Get the backend API path for a legal document.
 */
export function getLegalApiPath(document) {
  if (!document?.apiPath) {
    return null;
  }

  return String(
    document.apiPath
  ).trim() || null;
}

/* ============================================================================
 * Display helpers
 * ========================================================================== */

/**
 * Return a safe human-readable document label.
 */
export function getLegalDocumentLabel(
  document
) {
  if (!document) {
    return '';
  }

  return (
    document.shortTitle ||
    document.title ||
    document.slug ||
    document.id ||
    ''
  );
}

/**
 * Return a concise version label.
 */
export function getLegalVersionLabel(
  document
) {
  const version =
    getLegalDocumentVersion(
      document
    );

  return version
    ? `Version ${version}`
    : '';
}

/* ============================================================================
 * Legal document status helpers
 * ========================================================================== */

/**
 * Return a normalized status label.
 */
export function getLegalStatusLabel(
  document
) {
  const status =
    document?.status;

  if (!status) {
    return '';
  }

  return String(status)
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (letter) =>
      letter.toUpperCase()
    );
}

/**
 * Determine whether the document should appear in a legal navigation menu.
 */
export function shouldShowInLegalNavigation(
  document
) {
  return Boolean(
    document &&
    isPublicDocument(document) &&
    document.route
  );
}

/* ============================================================================
 * Supersession helpers
 * ========================================================================== */

/**
 * Determine whether a document references a predecessor.
 */
export function hasSupersededDocument(
  document
) {
  return Boolean(
    document?.supersedes
  );
}

/**
 * Determine whether a document has a successor.
 */
export function hasSuccessorDocument(
  document
) {
  return Boolean(
    document?.supersededBy
  );
}

/**
 * Resolve the predecessor document.
 */
export function getSupersededDocument(
  document
) {
  if (!document?.supersedes) {
    return null;
  }

  return resolveLegalDocument(
    document.supersedes
  );
}

/**
 * Resolve the successor document.
 */
export function getSuccessorLegalDocument(
  document
) {
  if (!document?.supersededBy) {
    return null;
  }

  return resolveLegalDocument(
    document.supersededBy
  );
}

/* ============================================================================
 * Content integrity helpers
 * ========================================================================== */

/**
 * Determine whether a legal document has a content integrity hash.
 *
 * The actual hash should be generated and verified by the backend/content
 * service. This function only checks metadata presence.
 */
export function hasContentHash(
  document
) {
  return Boolean(
    isNonEmptyString(
      document?.contentHash
    )
  );
}

/**
 * Return the registered content hash.
 */
export function getContentHash(
  document
) {
  if (!hasContentHash(document)) {
    return null;
  }

  return document.contentHash
    .trim();
}

/* ============================================================================
 * Registry statistics
 * ========================================================================== */

/**
 * Produce lightweight registry statistics.
 *
 * Useful for:
 *   - administration
 *   - development diagnostics
 *   - automated tests
 *   - observability
 */
export function getLegalRegistryStatistics() {
  const documents =
    LEGAL_DOCUMENTS;

  return Object.freeze({
    total: documents.length,

    published:
      documents.filter(
        (document) =>
          document.status ===
          LEGAL_STATUS.PUBLISHED
      ).length,

    public:
      documents.filter(
        (document) =>
          document.public === true
      ).length,

    acceptanceRequired:
      documents.filter(
        (document) =>
          document.requiresAcceptance === true
      ).length,

    critical:
      documents.filter(
        (document) =>
          document.priority ===
          LEGAL_PRIORITY.CRITICAL
      ).length,

    drafts:
      documents.filter(
        (document) =>
          document.status ===
          LEGAL_STATUS.DRAFT
      ).length,

    review:
      documents.filter(
        (document) =>
          document.status ===
          LEGAL_STATUS.REVIEW
      ).length,

    scheduled:
      documents.filter(
        (document) =>
          document.status ===
          LEGAL_STATUS.SCHEDULED
      ).length,

    superseded:
      documents.filter(
        (document) =>
          document.status ===
          LEGAL_STATUS.SUPERSEDED
      ).length,

    retired:
      documents.filter(
        (document) =>
          document.status ===
          LEGAL_STATUS.RETIRED
      ).length,
  });
}

/* ============================================================================
 * Development diagnostics
 * ========================================================================== */

/**
 * Log registry diagnostics without exposing legal content.
 *
 * Never log:
 *   - acceptance records
 *   - personal data
 *   - document contents
 *   - authentication data
 *   - secrets
 */
export function logLegalRegistryDiagnostics(
  logger = console
) {
  const validation =
    validateLegalConfiguration();

  const statistics =
    getLegalRegistryStatistics();

  if (
    validation.valid
  ) {
    logger.info(
      '[TITech Legal] Registry validation passed.',
      statistics
    );
  } else {
    logger.error(
      '[TITech Legal] Registry validation failed.',
      validation.errors
    );
  }

  return Object.freeze({
    validation,
    statistics,
  });
}

/* ============================================================================
 * Default export
 * ========================================================================== */

export default Object.freeze({
  validateLegalConfiguration,
  validateLegalDocument,

  normalizeLegalDocumentMetadata,
  normalizeLegalVersion,
  getLegalDocumentVersion,

  findLegalDocumentById,
  findLegalDocumentBySlug,
  resolveLegalDocument,

  isPublishedDocument,
  isPublicDocument,
  isApprovedDocument,
  isScheduledDocument,
  isRetiredDocument,
  isSupersededDocument,
  isPrePublicationDocument,

  isEffectiveDocument,
  isFutureEffectiveDocument,

  isAcceptanceRequired,
  requiresAcceptanceBeforeUse,
  requiresAcceptanceBeforeTransaction,
  requiresTenantAcceptance,
  requiresOrganizationAcceptance,
  requiresUserAcceptance,
  shouldLockAcceptedVersion,

  getVisiblePublicLegalDocuments,
  getCurrentLegalDocuments,
  getCriticalLegalDocuments,
  getDocumentsRequiringAcceptance,
  getTransactionLegalDocuments,

  searchLegalDocuments,

  formatLegalDate,
  formatEffectiveDate,

  getLegalRoute,
  getLegalApiPath,

  getLegalDocumentLabel,
  getLegalVersionLabel,
  getLegalStatusLabel,
  shouldShowInLegalNavigation,

  hasSupersededDocument,
  hasSuccessorDocument,
  getSupersededDocument,
  getSuccessorLegalDocument,

  hasContentHash,
  getContentHash,

  getLegalRegistryStatistics,
  logLegalRegistryDiagnostics,
});